Repository kubevirt/web-ui-components, pull requests merged in 2018-12, with the labels that each got.

#123 Add Templates Wizard and integration with Create Vm Wizard
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/ResultTab.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/constants.js
  src/components/Wizard/CreateVmWizard/fixtures/BasicSettingsTab.fixture.js
  src/components/Wizard/CreateVmWizard/fixtures/CreateVmWizard.fixture.js
  src/components/Wizard/CreateVmWizard/fixtures/NetworksTab.fixture.js
  src/components/Wizard/CreateVmWizard/fixtures/StorageTab.fixture.js
  src/components/Wizard/CreateVmWizard/strings.js
  src/components/Wizard/CreateVmWizard/tests/BasicSettingsTab.test.js
  src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js
  src/components/Wizard/CreateVmWizard/tests/NetworksTab.test.js
  src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/StorageTab.test.js.snap
  src/components/Wizard/CreateVmWizard/utils.js
  src/constants/index.js
  src/index.js
  src/k8s/mock_network/index.js
  src/k8s/mock_templates/index.js
  src/k8s/mock_user_templates/container-cloud.mock.js
  src/k8s/mock_user_templates/container-multus.mock.js
  src/k8s/mock_user_templates/container.mock.js
  src/k8s/mock_user_templates/index.js
  src/k8s/mock_user_templates/pxe-dv.mock.js
  src/k8s/mock_user_templates/pxe-pvc.mock.js
  src/k8s/mock_user_templates/pxe.mock.js
  src/k8s/mock_user_templates/url-flavor.mock.js
  src/k8s/mock_user_templates/url-nonetwork.mock.js
  src/k8s/mock_user_templates/url.mock.js
  src/k8s/mock_user_templates/windows.mock.js
  src/k8s/request.js
  src/k8s/selectors.js
  src/k8s/tests/request.test.js
  src/k8s/tests/selectors.test.js
  src/models/index.js
  src/utils/selectors.js
  src/utils/templates.js
  src/utils/tests/templates.test.js
Labels: size/XXL

#134 Add TemplateSource component
  sass/_components.scss
  sass/components/_TemplateSource.scss
  src/components/TemplateSource/TemplateSource.js
  src/components/TemplateSource/fixtures/TemplateSource.fixture.js
  src/components/TemplateSource/index.js
  src/components/TemplateSource/tests/TemplateSource.test.js
  src/components/TemplateSource/tests/__snapshots__/TemplateSource.test.js.snap
  src/index.js
Labels: size/L

#139 Update dependencies and bump React version
  package.json
  yarn.lock
Labels: size/M

#138 Rename registryDisk to containerDisk. #124
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/constants.js
  src/components/Wizard/CreateVmWizard/fixtures/BasicSettingsTab.fixture.js
  src/components/Wizard/CreateVmWizard/tests/BasicSettingsTab.test.js
  src/components/Wizard/CreateVmWizard/tests/NetworksTab.test.js
  src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
  src/constants/index.js
  src/k8s/mock_user_templates/container-cloud.mock.js
  src/k8s/mock_user_templates/container-multus.mock.js
  src/k8s/mock_user_templates/container.mock.js
  src/k8s/request.js
  src/k8s/tests/request.test.js
  src/utils/templates.js
  src/utils/tests/templates.test.js
Labels: size/L

#141 Move Loading component to folder
  src/components/Loading/Loading.js
  src/components/Loading/fixtures/Loading.fixture.js
  src/components/Loading/index.js
  src/components/Loading/tests/Loading.test.js
  src/components/Loading/tests/__snapshots__/Loading.test.js.snap
  src/components/TemplateSource/tests/__snapshots__/TemplateSource.test.js.snap
Labels: size/XS

#142 Bump 0.1.12
  package.json
Labels: size/XS

#146 Clone PVC disk for created VM. #145
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/constants/index.js
  src/k8s/request.js
  src/k8s/tests/request.test.js
  src/models/index.js
Labels: size/L

#148 export isBeingMigrated function
  src/components/VmStatus/getVmStatus.js
Labels: size/XS
