Repository kubevirt/web-ui-components, pull requests merged in 2018-11, with the labels that each got.

#80 Add correct boot order according to chosen image source
  src/k8s/request.js
  src/k8s/tests/request.test.js
Labels: size/M

#78 Require bootable disk for PXE and Template image sources
  src/components/Wizard/CreateVmWizard/StorageTab.js
Labels: size/S

#79 Add metadata to create VM - flavor, os, workload and used template
  src/constants/index.js
  src/k8s/mock_templates/fedora28.template.js
  src/k8s/mock_templates/rhel-high-p.template.js
  src/k8s/mock_templates/rhel75.template.js
  src/k8s/mock_templates/ubuntu1804.template.js
  src/k8s/mock_templates/windows.template.js
  src/k8s/request.js
  src/k8s/tests/request.test.js
Labels: size/M

#83 Make sure network is editable after initialization
  src/components/Wizard/CreateVmWizard/NetworksTab.js
Labels: size/XS

#85 Bump 0.1.7
  package.json
Labels: size/XS

#86 Add ids to basic settings form fields
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
Labels: size/S

#87 import-vm-apb template is using datavolumes not pvc
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/utils.js
  src/k8s/mock_user_templates/linux.template.js
  src/k8s/mock_user_templates/windows.template.js
  src/k8s/request.js
  src/k8s/selectors.js
  src/k8s/tests/request.test.js
  src/models/index.js
  src/utils/selectors.js
Labels: size/L

#88 import-vm-apb template is using datavolumes not pvc
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/utils.js
  src/k8s/mock_user_templates/linux.template.js
  src/k8s/mock_user_templates/windows.template.js
  src/k8s/request.js
  src/k8s/selectors.js
  src/k8s/tests/request.test.js
  src/models/index.js
  src/utils/selectors.js
Labels: size/L

#90 Bump 0.1.7-1
  package.json
Labels: size/XS

#93 Set firstBoot annotation to false if VM should start after creation
  src/k8s/request.js
  src/k8s/tests/request.test.js
Labels: size/S

#91 Add configurable URL Disk size
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/constants.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
  src/k8s/request.js
  src/k8s/tests/request.test.js
Labels: size/M

#92 Add configurable URL Disk size
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/constants.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
  src/k8s/request.js
  src/k8s/tests/request.test.js
Labels: size/M

#89 NewVmWizard: fix fixture
  src/components/Wizard/NewVmWizard/fixtures/NewVmWizard.fixture.js
Labels: size/XS

#97 Bump 0.1.7-2
  package.json
Labels: size/XS

#95 Add PXE boot patch util method
  src/constants/index.js
  src/index.js
  src/k8s/request.js
  src/utils/index.js
  src/utils/selectors.js
  src/utils/tests/utils.test.js
  src/utils/utils.js
Labels: size/L

#98 remove NewVmWizard
  src/components/Wizard/CreateVmWizard/fixtures/BasicSettingsTab.fixture.js
  src/components/Wizard/CreateVmWizard/fixtures/CreateVmWizard.fixture.js
  src/components/Wizard/CreateVmWizard/fixtures/StorageTab.fixture.js
  src/components/Wizard/CreateVmWizard/tests/BasicSettingsTab.test.js
  src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js
  src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js
  src/components/Wizard/NewVmWizard/NewVmWizard.js
  src/components/Wizard/NewVmWizard/fixtures/NewVmWizard.fixture.js
  src/components/Wizard/NewVmWizard/index.js
  src/components/Wizard/NewVmWizard/tests/NewVmWizard.test.js
  src/components/Wizard/NewVmWizard/tests/__snapshots__/NewVmWizard.test.js.snap
  src/index.js
  src/k8s/tests/request.test.js
Labels: size/L

#69 Use integer input type for CPU and Memory fields
  src/components/Form/Integer.js
  src/components/Form/tests/Integer.test.js
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/tests/BasicSettingsTab.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
Labels: size/M

#101 Remove tools folder from coverate report
  config/jest.config.js
Labels: size/XS

#99 Add Loading to Create VM Wizard tabs.
  src/components/Loading.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/ResultTab.js
  src/components/Wizard/CreateVmWizard/fixtures/BasicSettingsTab.fixture.js
  src/components/Wizard/CreateVmWizard/fixtures/CreateVmWizard.fixture.js
  src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/ResultTab.test.js.snap
  src/components/Wizard/loadingWizardTab.js
  src/components/Wizard/tests/loadingWizardTab.test.js
  src/components/fixtures/Loading.fixture.js
  src/components/tests/Loading.test.js
  src/components/tests/__snapshots__/Loading.test.js.snap
Labels: size/L

#102 Cloud-init fields are not required
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
  src/k8s/request.js
  src/k8s/tests/request.test.js
Labels: size/M

#100 NetworksTab: Make constants out of strings and add tests
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/constants.js
  src/components/Wizard/CreateVmWizard/strings.js
  src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js
  src/components/Wizard/CreateVmWizard/tests/NetworksTab.test.js
Labels: size/L

#106 Tweak code converage reports:
  config/jest.config.js
  src/constants/index.js
  src/k8s/mock_network/network.mock.js
  src/k8s/mock_network/network2.mock.js
  src/k8s/mock_templates/fedora28.mock.js
  src/k8s/mock_templates/rhel-high-p.mock.js
  src/k8s/mock_templates/rhel75.mock.js
  src/k8s/mock_templates/ubuntu1804.mock.js
  src/k8s/mock_templates/windows.mock.js
  src/k8s/mock_user_templates/linux.mock.js
  src/k8s/mock_user_templates/windows.mock.js
  src/k8s/tests/request.test.js
Labels: size/S

#110 add migration dialog
  src/components/Dialog/BasicMigrationDialog/BasicMigrationDialog.js
  src/components/Dialog/BasicMigrationDialog/fixtures/BasicMigrationDialog.fixture.js
  src/components/Dialog/BasicMigrationDialog/index.js
  src/components/Dialog/BasicMigrationDialog/tests/BasicMigrationDialog.test.js
  src/components/Dialog/BasicMigrationDialog/tests/__snapshots__/BasicMigrationDialog.test.js.snap
  src/index.js
  src/k8s/migrate.js
  src/k8s/mock_vmi/blue.vmi.js
  src/k8s/selectors.js
  src/k8s/tests/migrate.test.js
  src/models/index.js
Labels: size/L

#105 Add VM name validation against DNS1123 subdomain spec
  src/components/Form/FormFactory.js
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/strings.js
  src/components/Wizard/CreateVmWizard/tests/BasicSettingsTab.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/NetworksTab.test.js.snap
  src/constants/index.js
  src/utils/strings.js
  src/utils/tests/validation.test.js
  src/utils/validations.js
Labels: size/L

#112 Bump 0.1.8
  package.json
Labels: size/XS

#114 Bump 0.1.9
  package.json
Labels: size/XS

#115 Introduce VmConsoles component
  config/jest.config.js
  package.json
  sass/_components.scss
  sass/components/_VmConsoles.scss
  src/components/VmConsoles/SerialConsoleConnector.js
  src/components/VmConsoles/VmConsoles.js
  src/components/VmConsoles/fixtures/SerialConsoleConnector.fixture.js
  src/components/VmConsoles/fixtures/VmConsoles.fixture.js
  src/components/VmConsoles/index.js
  src/components/VmConsoles/tests/SerialConsoleConnector.test.js
  src/components/VmConsoles/tests/VmConsoles.test.js
  src/components/VmConsoles/tests/__snapshots__/SerialConsoleConnector.test.js.snap
  src/components/VmConsoles/tests/__snapshots__/VmConsoles.test.js.snap
  src/components/VmStatus/getVmStatus.js
  src/index.js
  src/jest/polyfills.js
  src/jest/setupTest.js
  yarn.lock
Labels: size/XL

#116 Bump 0.1.10
  package.json
Labels: size/XS

#117 Upgrade @patternfly/react-console to 1.9.1
  package.json
  yarn.lock
Labels: size/S

#113 Use object instead of array in CreateVmWizard stepData. #77
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/constants.js
  src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap
  src/components/Wizard/CreateVmWizard/utils.js
  src/utils/templates.js
  src/utils/tests/templates.test.js
Labels: size/L

#118 Fix VmConsoles: provide VncConsole type
  src/components/VmConsoles/VmConsoles.js
Labels: size/XS

#119 Bump 0.1.11
  package.json
Labels: size/XS

#126 Add disabled property for Form controls
  src/components/Form/Checkbox.js
  src/components/Form/Dropdown.js
  src/components/Form/FormFactory.js
  src/components/Form/Integer.js
  src/components/Form/Text.js
  src/components/Form/TextArea.js
  src/components/Form/tests/__snapshots__/Dropdown.test.js.snap
  src/components/Form/tests/__snapshots__/FormFactory.test.js.snap
  src/components/Form/tests/__snapshots__/Integer.test.js.snap
  src/components/Form/tests/__snapshots__/Text.test.js.snap
  src/components/Form/tests/__snapshots__/TextArea.test.js.snap
Labels: size/M

#125 Introduce VM_STATUS_VMI_WAITING state
  src/components/VmStatus/VmStatus.js
  src/components/VmStatus/fixtures/VmStatus.fixture.js
  src/components/VmStatus/getVmStatus.js
  src/components/VmStatus/tests/VmStatus.test.js
  src/components/VmStatus/tests/__snapshots__/VmStatus.test.js.snap
  src/constants/index.js
Labels: size/L
