Repository kubevirt/web-ui-components, pull requests merged in 2018-10, with the labels that each got.

#34 Add Template provision source which works with import-vm-apb templates
  src/components/Wizards/CreateVmWizard/CreateVmWizard.js
  src/components/Wizards/CreateVmWizard/fixtures/CreateVmWizard.fixture.js
  src/components/Wizards/CreateVmWizard/tests/CreateVmWizard.test.js
  src/components/Wizards/NewVmWizard/fixtures/NewVmWizard.fixture.js
  src/components/Wizards/NewVmWizard/tests/NewVmWizard.test.js
  src/constants/index.js
  src/k8s/mock_user_templates/linux.template.js
  src/k8s/mock_user_templates/windows.template.js
  src/k8s/request.js
  src/k8s/tests/request.test.js
  src/models/index.js
Labels: size/XL

#36 Bump 0.1.3
  package.json
Labels: size/XS

#38 Editable Draggable Table component
  package.json
  sass/_components.scss
  sass/components/_EditableDraggableTable.scss
  sass/components/_ResultTab.scss
  src/components/Table/EditableDraggableTable.js
  src/components/Table/InlineEditRow.js
  src/components/Table/constants.js
  src/components/Table/fixtures/EditableDraggableTable.fixture.js
  src/components/Table/fixtures/InlineEditRow.fixture.js
  src/components/Table/tests/EditableDraggableTable.test.js
  src/components/Table/tests/InlineEditRow.test.js
  src/components/Table/tests/__snapshots__/EditableDraggableTable.test.js.snap
  src/components/Table/tests/__snapshots__/InlineEditRow.test.js.snap
  tools/validations/componentFriends.js
  yarn.lock
Labels: size/XL

#39 Export all constants
  src/index.js
Labels: size/XS

#40 initialize Create VM Dialog with selectedNamespace
  src/components/Forms/FormFactory.js
  src/components/Wizards/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizards/CreateVmWizard/CreateVmWizard.js
  src/components/Wizards/CreateVmWizard/fixtures/CreateVmWizard.fixture.js
  src/components/Wizards/CreateVmWizard/tests/BasicSettingsTab.test.js
Labels: size/L

#45 Make Table action text configurable. Fixes #44
  src/components/Table/EditableDraggableTable.js
  src/components/Wizards/CreateVmWizard/NetworksTab.js
Labels: size/S

#47 Use declarative approach for table column's renderConfigs. Fixes #46
  src/components/Table/EditableDraggableTable.js
  src/components/Wizards/CreateVmWizard/NetworksTab.js
  src/components/Wizards/CreateVmWizard/tests/__snapshots__/NetworksTab.test.js.snap
Labels: size/M

#56 Preselect template for user template provision source
  src/components/Wizards/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizards/CreateVmWizard/tests/BasicSettingsTab.test.js
Labels: size/M

#62 CreateVmWizard: disable cancel button in the last step (fix #61)
  src/components/Wizards/CreateVmWizard/CreateVmWizard.js
  src/components/Wizards/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap
  yarn.lock
Labels: size/M

#50 Use default network model, if defined
  src/components/Wizards/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
  src/constants/index.js
  src/k8s/mock_templates/windows.template.js
  src/k8s/request.js
  src/k8s/tests/request.test.js
  src/k8s/tests/selectors.test.js
Labels: size/L

#68 Fix "main" JS entry
  package.json
Labels: size/XS

#65 Use common-templates if they are available
  src/k8s/selectors.js
Labels: size/XS

#52 Allow disabling VM's pod network
  src/components/Wizards/CreateVmWizard/NetworksTab.js
  src/components/Wizards/CreateVmWizard/tests/__snapshots__/NetworksTab.test.js.snap
  src/k8s/mock_templates/fedora28.template.js
  src/k8s/mock_templates/rhel-high-p.template.js
  src/k8s/mock_templates/rhel75.template.js
  src/k8s/mock_templates/ubuntu1804.template.js
  src/k8s/request.js
  src/k8s/tests/request.test.js
Labels: size/L

#54 Remove cloudinit disk and volume if cloudinit is not used
  src/k8s/mock_templates/fedora28.template.js
  src/k8s/mock_templates/rhel-high-p.template.js
  src/k8s/mock_templates/rhel75.template.js
  src/k8s/request.js
  src/k8s/tests/request.test.js
Labels: size/L

#66 Make constants out of pxe annotations
  src/constants/index.js
  src/k8s/request.js
  src/k8s/tests/request.test.js
Labels: size/M

#67 Move template util methods to utils/templates
  src/components/Wizards/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizards/CreateVmWizard/tests/BasicSettingsTab.test.js
  src/k8s/request.js
  src/k8s/selectors.js
  src/k8s/tests/selectors.test.js
  src/utils/templates.js
  src/utils/tests/validation.test.js
  src/utils/validations.js
Labels: size/M

#33 Deploy Cosmos to gh-pages branch upon pushing to master branch
  .travis.yml
  config/cosmos.webpack.config.js
  config/eslint.browser.js
  deploy_key.enc
  package.json
  tools/common.js
  tools/runValidations.js
  tools/travis/afterSuccess.js
  tools/travis/beforeScript.js
  tools/travis/env.js
  tools/travis/execShell.js
  tools/travis/tasks/addGhDeployKey.js
  tools/travis/tasks/deployCosmosToGhPages.js
  tools/travis/tasks/exportCosmos.js
  tools/validations/componentFriends.js
  tools/validations/dependencyPeerAsDev.js
  tools/validations/dependencySemverFormat.js
  yarn.lock
Labels: size/L

#72 Bump 0.1.5
  package.json
Labels: size/XS

#73 Ensure that ssh-agent is running on CI workers
  .travis.yml
  tools/travis/tasks/addGhDeployKey.js
  tools/travis/tasks/deployCosmosToGhPages.js
Labels: size/XS

#74 Turn off Jekyll when served via GitHub Pages
  tools/travis/tasks/exportCosmos.js
Labels: size/XS

#55 Choose bootable network with dropdown
  sass/components/_NetworksTab.scss
  src/components/Form/FormFactory.js
  src/components/Form/tests/__snapshots__/FormFactory.test.js.snap
  src/components/Table/TableFactory.js
  src/components/Table/tests/TableFactory.test.js
  src/components/Wizards/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizards/CreateVmWizard/NetworksTab.js
  src/components/Wizards/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
  src/components/Wizards/CreateVmWizard/tests/__snapshots__/NetworksTab.test.js.snap
  src/constants/index.js
  src/k8s/mock_network/network2.template.js
Labels: size/L

#63 Support URL and Registry image sources in StorageTab
  sass/_components.scss
  sass/components/_StorageTab.scss
  src/components/Table/EditableDraggableTable.js
  src/components/Table/tests/EditableDraggableTable.test.js
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/ResultTab.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/constants.js
  src/components/Wizard/CreateVmWizard/fixtures/BasicSettingsTab.fixture.js
  src/components/Wizard/CreateVmWizard/fixtures/CreateVmWizard.fixture.js
  src/components/Wizard/CreateVmWizard/fixtures/NetworksTab.fixture.js
  src/components/Wizard/CreateVmWizard/fixtures/ResultTab.fixture.js
  src/components/Wizard/CreateVmWizard/fixtures/StorageTab.fixture.js
  src/components/Wizard/CreateVmWizard/index.js
  src/components/Wizard/CreateVmWizard/tests/BasicSettingsTab.test.js
  src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js
  src/components/Wizard/CreateVmWizard/tests/NetworksTab.test.js
  src/components/Wizard/CreateVmWizard/tests/ResultTab.test.js
  src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/NetworksTab.test.js.snap
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/ResultTab.test.js.snap
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/StorageTab.test.js.snap
  src/components/Wizard/CreateVmWizard/utils.js
  src/components/Wizard/NewVmWizard/NewVmWizard.js
  src/components/Wizard/NewVmWizard/fixtures/NewVmWizard.fixture.js
  src/components/Wizard/NewVmWizard/index.js
  src/components/Wizard/NewVmWizard/tests/NewVmWizard.test.js
  src/components/Wizard/NewVmWizard/tests/__snapshots__/NewVmWizard.test.js.snap
  src/components/Wizards/CreateVmWizard/CreateVmWizard.js
  src/index.js
  src/k8s/request.js
  src/k8s/selectors.js
  src/k8s/tests/request.test.js
  src/utils/selectors.js
Labels: blocked, size/XXL

#82 Bump 0.1.6
  package.json
Labels: size/XS
