Repository kubevirt/web-ui-components, pull requests merged in 2019-06, with the labels that each got.

#486 CreateVmDialog: V2V VMware report deployment status/errors
  src/components/VmStatus/tests/VmStatus.test.js
  src/components/Wizard/CreateVmWizard/initialState/providers/vmWareInitialState.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/VMWareControllerErrors.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/VMWareControllerStatusRow.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/VMWareImportProvider.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/VMWareObjectStatus.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/VMwareStatusField.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/constants.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/fixtures/VMWareControllerErrors.fixture.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/fixtures/VMWareControllerStatusRow.fixture.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/fixtures/VMWareObjectStatus.fixture.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/fixtures/VMwareStatusField.fixture.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/requestedResources.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/VMWareControllerErrors.test.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/VMWareControllerStatusRow.test.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/VMWareImportProvider.test.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/VMWareObjectStatus.test.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/VMwareStatusField.test.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/__snapshots__/VMWareControllerErrors.test.js.snap
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/__snapshots__/VMWareControllerStatusRow.test.js.snap
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/__snapshots__/VMWareImportProvider.test.js.snap
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/__snapshots__/VMWareObjectStatus.test.js.snap
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/__snapshots__/VMwareStatusField.test.js.snap
  src/components/Wizard/CreateVmWizard/stateUpdate/providers/vmWareStateUpdate.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap
  src/k8s/requests/v2v/startV2VvmwareController.js
  src/k8s/util/k8sMethodsUtils.js
  src/selectors/common.js
  src/tests/mocks/v2v/VMWareDeploymentPod.js
  src/tests/mocks/v2v/VMwareDeployment.js
  src/tests/mocks/v2v/index.js
  src/tests/router/index.js
  src/tests/router/router.js
  src/utils/status/deployment/constants.js
  src/utils/status/deployment/deploymentStatus.js
  src/utils/status/deployment/fixtures/deploymentStatus.fixture.js
  src/utils/status/deployment/index.js
  src/utils/status/deployment/tests/deploymentStatus.test.js
  src/utils/status/pod/podStatus.js
  src/utils/status/pod/tests/podStatus.test.js
  src/utils/status/v2vVMwareDeployment/constants.js
  src/utils/status/v2vVMwareDeployment/fixtures/v2vVMwareDeploymentStatus.fixture.js
  src/utils/status/v2vVMwareDeployment/index.js
  src/utils/status/v2vVMwareDeployment/tests/v2vVMwareDeploymentStatus.test.js
  src/utils/status/v2vVMwareDeployment/v2vVMwareDeploymentStatus.js
Labels: size/XXL

#490 Bump 0.1.34-7
  package.json
Labels: size/XS

#487 CreateVmWizard WMware - fix: fields become inactive after the VM is picked
  src/components/Wizard/CreateVmWizard/stateUpdate/providers/vmWareStateUpdate.js
Labels: size/S

#491 Use k8s generateName for migration objects
  src/k8s/migrate.js
  src/k8s/tests/migrate.test.js
  src/tests/k8s.js
Labels: size/S

#492 Use k8s generateName for migration objects
  src/k8s/migrate.js
  src/k8s/tests/migrate.test.js
  src/tests/k8s.js
Labels: size/S

#489 Fix save vCenter credentials functionality
  src/components/Wizard/CreateVmWizard/initialState/providers/vmWareInitialState.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/VMWareImportProvider.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/constants.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/fixtures/VMWareImportProvider.fixture.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/VMWareImportProvider.test.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/__snapshots__/VMWareImportProvider.test.js.snap
  src/components/Wizard/CreateVmWizard/stateUpdate/providers/vmWareStateUpdate.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap
  src/k8s/requests/v2v/createV2VvmwareObject.js
  src/k8s/requests/v2v/importVmware.js
  src/k8s/tests/request.test.js
  src/selectors/v2v/selectors.js
  src/utils/patches.js
  src/utils/tests/patches.test.js
Labels: size/XXL

#493 Fix save vCenter credentials functionality
  src/components/Wizard/CreateVmWizard/initialState/providers/vmWareInitialState.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/VMWareImportProvider.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/constants.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/fixtures/VMWareImportProvider.fixture.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/__snapshots__/VMWareImportProvider.test.js.snap
  src/components/Wizard/CreateVmWizard/stateUpdate/providers/vmWareStateUpdate.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap
  src/k8s/requests/v2v/createV2VvmwareObject.js
  src/k8s/requests/v2v/importVmware.js
  src/k8s/tests/request.test.js
  src/selectors/v2v/selectors.js
  src/utils/patches.js
  src/utils/tests/patches.test.js
Labels: size/L

#495 Change PVC access mode to RWM
  src/components/ClusterOverview/Inventory/tests/__snapshots__/Inventory.test.js.snap
  src/components/VmConsoles/tests/__snapshots__/DesktopViewerSelector.test.js.snap
  src/constants/index.js
  src/k8s/objects/pvc/pvc.js
  src/k8s/vmBuilder.js
  src/tests/mocks/dataVolume/index.js
  src/tests/mocks/user_template/pvc.mock.js
  src/tests/mocks/user_template/pxe-dv.mock.js
  src/tests/mocks/user_template/url-flavor.mock.js
  src/tests/mocks/user_template/url-nonetwork.mock.js
  src/tests/mocks/user_template/url.mock.js
  src/tests/mocks/vm/vm.mock.js
  src/tests/mocks/vm/vm_validation.mock.js
  src/utils/patches.js
  src/utils/tests/patches.test.js
Labels: size/M

#497 Fix re-exports
  src/components/Details/VmDetails/VmDetails.js
  src/components/Details/index.js
  src/index.js
  src/k8s/index.js
  src/selectors/index.js
  src/utils/status/vm/vmStatus.js
Labels: size/S

#496 Change PVC access mode to RWM
  src/components/VmConsoles/tests/__snapshots__/DesktopViewerSelector.test.js.snap
  src/constants/index.js
  src/k8s/objects/pvc/pvc.js
  src/k8s/vmBuilder.js
  src/tests/mocks/dataVolume/index.js
  src/tests/mocks/user_template/pvc.mock.js
  src/tests/mocks/user_template/pxe-dv.mock.js
  src/tests/mocks/user_template/url-flavor.mock.js
  src/tests/mocks/user_template/url-nonetwork.mock.js
  src/tests/mocks/user_template/url.mock.js
  src/tests/mocks/vm/vm.mock.js
  src/tests/mocks/vm/vm_validation.mock.js
  src/utils/patches.js
  src/utils/tests/patches.test.js
Labels: size/M

#498 getResource: add `optional` property
  src/utils/utils.js
Labels: size/S

#499 Bump 0.1.35
  package.json
Labels: size/XS

#475 Capacity Card Dropdown
  sass/components/Dashboard/capacity.scss
  src/components/StorageOverview/Capacity/Capacity.js
  src/components/StorageOverview/Capacity/fixtures/Capacity.fixture.js
  src/components/StorageOverview/Capacity/strings.js
  src/components/StorageOverview/Capacity/tests/Capacity.test.js
  src/components/StorageOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/constants/storage.js
Labels: size/L

#481 added dropdown for VMs in top consumers card
  src/components/StorageOverview/TopConsumers/TopConsumers.js
  src/components/StorageOverview/TopConsumers/strings.js
  src/components/StorageOverview/TopConsumers/tests/TopConsumers.test.js
  src/components/StorageOverview/TopConsumers/tests/__snapshots__/TopConsumers.test.js.snap
  src/selectors/prometheus/storage.js
Labels: size/M

#501 V2V: Listen on active VCenter Secret only when import provider is active
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/initialState/providers/vmWareInitialState.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/VMWareImportProvider.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/constants.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/requestedResources.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/__snapshots__/VMWareImportProvider.test.js.snap
  src/components/Wizard/CreateVmWizard/stateUpdate/providers/vmWareStateUpdate.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap
  src/k8s/requests/v2v/correctVCenterSecretLabels.js
Labels: size/L

#502 ProcessedTemplatesModel: add "plural" prop
  src/models/index.js
Labels: size/XS

#503 CreateVmDialog uses Firehose
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/VMWareImportProvider.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/requestedResources.js
  src/k8s/util/k8sMethodsUtils.js
Labels: size/M

#504 Bump 0.1.36
  package.json
Labels: size/XS

#505 flatten activeVcenterSecret
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/VMWareImportProvider.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/requestedResources.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/__snapshots__/VMWareImportProvider.test.js.snap
Labels: size/S
