Repository kubevirt/web-ui-components, pull requests merged in 2019-10, with the labels that each got.

#556 Bump 0.1.45
  package.json
Labels: dco-signoff: no, size/XS

#558 export v2v request functions + few fixes
  src/k8s/index.js
  src/k8s/requests/v2v/correctVCenterSecretLabels.js
  src/k8s/requests/v2v/createV2VvmwareObject.js
  src/k8s/requests/v2v/importVmware.js
  src/k8s/requests/v2v/index.js
  src/k8s/requests/v2v/startV2VvmwareController.js
Labels: dco-signoff: yes, size/M

#557 v2v-conversion-pod: Use volumeDevices for Block volumeMode
  src/components/Wizard/CreateVmWizard/stateUpdate/providers/prefillVmStateUpdate.js
  src/k8s/objects/v2v/vmware/conversionPod.js
  src/k8s/requests/v2v/importVmware.js
  src/selectors/pvc/selectors.js
Labels: dco-signoff: yes, size/M

#560 Bump 0.1.47
  package.json
Labels: dco-signoff: yes, size/XS

#561 Always use RWO accessMode for conversion pod temporary disk
  src/k8s/requests/v2v/importVmware.js
Labels: dco-signoff: yes, size/XS

#563 Bump 0.1.48
  package.json
Labels: dco-signoff: yes, size/XS

#565 Backport 557, BZ 1756328: Use volumeDevices for Block volumeMode
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/VMWareImportProvider.js
  src/components/Wizard/CreateVmWizard/stateUpdate/providers/prefillVmStateUpdate.js
  src/k8s/objects/v2v/vmware/conversionPod.js
  src/k8s/requests/v2v/importVmware.js
  src/k8s/requests/v2v/startV2VvmwareController.js
  src/selectors/pvc/selectors.js
Labels: dco-signoff: yes, size/M

#566 Backport 561, BZ 1756328:
  src/k8s/requests/v2v/importVmware.js
Labels: dco-signoff: yes, size/XS

#567 Bump 0.1.44.1
  package.json
Labels: dco-signoff: yes, size/XS

#569 v2v: add VM name to the conversion pod name
  src/k8s/objects/v2v/vmware/conversionPod.js
  src/k8s/requests/v2v/importVmware.js
  src/selectors/pod/combined.js
Labels: dco-signoff: yes, size/S

#570 Bump 0.1.49
  package.json
Labels: dco-signoff: yes, size/XS
