Repository kubevirt/web-ui-components, pull requests merged in 2019-03, with the labels that each got.

#243 v2v: prefill Name and Description based on VMWare VM
  src/components/Form/FormFactory.js
  src/components/Form/index.js
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/constants.js
  src/components/Wizard/CreateVmWizard/providers/VCenterVms.js
  src/components/Wizard/CreateVmWizard/providers/VCenterVmsWithPrefill.js
  src/components/Wizard/CreateVmWizard/providers/fixtures/VCenterVmsWithPrefill.fixture.js
  src/components/Wizard/CreateVmWizard/providers/tests/VCenterVms.test.js
  src/components/Wizard/CreateVmWizard/providers/tests/VCenterVmsWithPrefill.test.js
  src/components/Wizard/CreateVmWizard/providers/tests/__snapshots__/VCenterVmsWithPrefill.test.js.snap
  src/components/Wizard/CreateVmWizard/providers/tests/vmwareActions.test.js
  src/components/Wizard/CreateVmWizard/providers/vmwareActions.js
  src/tests/k8s.js
Labels: size/XL

#244 v2v: Delete V2VVMWare object on CreateVmWizard close
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/providers/VCenterVms.js
  src/components/Wizard/CreateVmWizard/providers/vmwareActions.js
  src/components/Wizard/CreateVmWizard/tests/BasicSettingsTab.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap
  src/k8s/selectors.js
  src/tests/k8s.js
Labels: size/M

#248 add ids to components
  src/components/Details/Description/Description.js
  src/components/Details/Description/tests/Description.test.js
  src/components/Details/Description/tests/__snapshots__/Description.test.js.snap
  src/components/Details/Flavor/Flavor.js
  src/components/Details/Flavor/tests/Flavor.test.js
  src/components/Details/Flavor/tests/__snapshots__/Flavor.test.js.snap
  src/components/Details/VmDetails/VmDetails.js
  src/components/Details/VmDetails/tests/VmDetails.test.js
  src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap
  src/components/Details/VmTemplateDetails/VmTemplateDetails.js
  src/components/Details/VmTemplateDetails/tests/VmTemplateDetails.test.js
  src/components/Details/VmTemplateDetails/tests/__snapshots__/VmTemplateDetails.test.js.snap
  src/components/Details/common/tests/details.js
  src/components/InlineEdit/InlineEdit.js
  src/components/Loading/Loading.js
  src/components/TemplateSource/TemplateSource.js
  src/utils/selectors.js
Labels: size/XL

#199 Add view-only boot order component to VM details dialog
  sass/_components.scss
  sass/components/VmDetails/boot-order.scss
  src/components/Details/BootOrder/BootOrder.js
  src/components/Details/BootOrder/fixtures/BootOrder.fixture.js
  src/components/Details/BootOrder/index.js
  src/components/Details/BootOrder/tests/BootOrder.test.js
  src/components/Details/BootOrder/tests/__snapshots__/BootOrder.test.js.snap
  src/components/Details/VmDetails/VmDetails.js
  src/components/Details/VmDetails/fixtures/VmDetails.fixture.js
  src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap
  src/components/Details/VmTemplateDetails/VmTemplateDetails.js
  src/components/Details/VmTemplateDetails/tests/__snapshots__/VmTemplateDetails.test.js.snap
  src/constants/index.js
  src/k8s/request.js
  src/k8s/tests/request.test.js
  src/k8s/vmBuilder.js
  src/utils/patches.js
  src/utils/tests/patches.test.js
Labels: size/XL

#249 v2v: prefill operating system
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/providers/VCenterVms.js
  src/components/Wizard/CreateVmWizard/providers/VCenterVmsWithPrefill.js
  src/components/Wizard/CreateVmWizard/providers/index.js
  src/components/Wizard/CreateVmWizard/providers/tests/VCenterVms.test.js
  src/components/Wizard/CreateVmWizard/providers/tests/VCenterVmsWithPrefill.test.js
  src/components/Wizard/CreateVmWizard/providers/tests/__snapshots__/VCenterVmsWithPrefill.test.js.snap
  src/components/Wizard/CreateVmWizard/providers/vmware.js
  src/components/Wizard/CreateVmWizard/providers/vmwareActions.js
  src/components/Wizard/CreateVmWizard/strings.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
  src/constants/index.js
  src/models/index.js
  src/tests/k8s.js
Labels: size/L

#252 v2v: prefill cpu and memory
  src/components/Wizard/CreateVmWizard/providers/VCenterVmsWithPrefill.js
  src/components/Wizard/CreateVmWizard/providers/tests/VCenterVmsWithPrefill.test.js
Labels: size/L

#253 v2v: add more unit tests
  src/components/Wizard/CreateVmWizard/providers/VCenterVmsWithPrefill.js
  src/components/Wizard/CreateVmWizard/providers/tests/VCenterVmsWithPrefill.test.js
Labels: size/M

#256 v2v: prefill networks
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/constants.js
  src/components/Wizard/CreateVmWizard/fixtures/NetworksTab.fixture.js
  src/components/Wizard/CreateVmWizard/providers/VCenterVmsWithPrefill.js
  src/components/Wizard/CreateVmWizard/providers/tests/VCenterVmsWithPrefill.test.js
  src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js
Labels: size/L

#246 Details: remove search&hash elipsization
  src/components/Details/Url/Url.js
  src/components/Details/Url/tests/__snapshots__/Url.test.js.snap
  src/components/Details/VmTemplateDetails/tests/__snapshots__/VmTemplateDetails.test.js.snap
Labels: size/S

#245 Improve VM details styling for overview view
  sass/components/VmDetails/vm-details.scss
  src/components/Details/Description/Description.js
  src/components/Details/VmDetails/VmDetails.js
  src/components/Details/VmDetails/fixtures/VmDetails.fixture.js
  src/components/Details/VmDetails/tests/VmDetails.test.js
  src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap
  src/tests/k8s.js
Labels: size/XXL

#259 v2v: prefill disks
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/constants.js
  src/components/Wizard/CreateVmWizard/providers/VCenterVmsWithPrefill.js
  src/components/Wizard/CreateVmWizard/providers/tests/VCenterVmsWithPrefill.test.js
  src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js
Labels: size/L

#257 Host status selector
  src/index.js
  src/models/index.js
  src/utils/selectors.js
Labels: size/S

#247 Add Cluster Overview
  sass/_components.scss
  sass/components/ClusterOverview/capacity.scss
  sass/components/ClusterOverview/cluster-overview.scss
  sass/components/ClusterOverview/consumers.scss
  sass/components/ClusterOverview/detail.scss
  sass/components/ClusterOverview/events.scss
  sass/components/ClusterOverview/health.scss
  sass/components/ClusterOverview/inventory.scss
  sass/components/ClusterOverview/utilization.scss
  src/components/ClusterOverview/Capacity/Capacity.js
  src/components/ClusterOverview/Capacity/fixtures/Capacity.fixture.js
  src/components/ClusterOverview/Capacity/tests/Capacity.test.js
  src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/ClusterOverview/ClusterOverview.js
  src/components/ClusterOverview/Consumers/Consumers.js
  src/components/ClusterOverview/Consumers/fixtures/Consumers.fixture.js
  src/components/ClusterOverview/Consumers/tests/Consumers.test.js
  src/components/ClusterOverview/Consumers/tests/__snapshots__/Consumers.test.js.snap
  src/components/ClusterOverview/Details/Details.js
  src/components/ClusterOverview/Details/fixtures/Details.fixture.js
  src/components/ClusterOverview/Details/tests/Details.test.js
  src/components/ClusterOverview/Details/tests/__snapshots__/Details.test.js.snap
  src/components/ClusterOverview/Events/Events.js
  src/components/ClusterOverview/Events/fixtures/Events.fixture.js
  src/components/ClusterOverview/Events/tests/Events.test.js
  src/components/ClusterOverview/Events/tests/__snapshots__/Events.test.js.snap
  src/components/ClusterOverview/Health/Health.js
  src/components/ClusterOverview/Health/fixtures/Health.fixture.js
  src/components/ClusterOverview/Health/tests/Health.test.js
  src/components/ClusterOverview/Health/tests/__snapshots__/Health.test.js.snap
  src/components/ClusterOverview/Inventory/Inventory.js
  src/components/ClusterOverview/Inventory/fixtures/Inventory.fixture.js
  src/components/ClusterOverview/Inventory/nodeStatus.js
  src/components/ClusterOverview/Inventory/tests/Inventory.test.js
  src/components/ClusterOverview/Inventory/tests/__snapshots__/Inventory.test.js.snap
  src/components/ClusterOverview/Utilization/Utilization.js
  src/components/ClusterOverview/Utilization/fixtures/Utilization.fixture.js
  src/components/ClusterOverview/Utilization/tests/Utilization.test.js
  src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/ClusterOverview/fixtures/ClusterOverview.fixture.js
  src/components/ClusterOverview/index.js
  src/components/ClusterOverview/tests/ClusterOverview.test.js
  src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
  src/components/Loading/Loading.js
  src/components/Loading/tests/__snapshots__/Loading.test.js.snap
  src/index.js
  src/utils/selectors.js
  src/utils/utils.js
Labels: size/XXL

#269 Introduce ClusterOverviewContext component
  src/components/ClusterOverview/Capacity/Capacity.js
  src/components/ClusterOverview/Capacity/fixtures/Capacity.fixture.js
  src/components/ClusterOverview/Capacity/tests/Capacity.test.js
  src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/ClusterOverview/ClusterOverview.js
  src/components/ClusterOverview/ClusterOverviewContext/ClusterOverviewContext.js
  src/components/ClusterOverview/ClusterOverviewContext/fixtures/ClusterOverviewContext.fixture.js
  src/components/ClusterOverview/ClusterOverviewContext/index.js
  src/components/ClusterOverview/ClusterOverviewContext/tests/ClusterOverviewContext.test.js
  src/components/ClusterOverview/ClusterOverviewContext/tests/__snapshots__/ClusterOverviewContext.test.js.snap
  src/components/ClusterOverview/Compliance/Compliance.js
  src/components/ClusterOverview/Compliance/fixtures/Compliance.fixture.js
  src/components/ClusterOverview/Compliance/tests/Compliance.test.js
  src/components/ClusterOverview/Compliance/tests/__snapshots__/Compliance.test.js.snap
  src/components/ClusterOverview/Details/Details.js
  src/components/ClusterOverview/Details/fixtures/Details.fixture.js
  src/components/ClusterOverview/Details/tests/Details.test.js
  src/components/ClusterOverview/Details/tests/__snapshots__/Details.test.js.snap
  src/components/ClusterOverview/Events/Events.js
  src/components/ClusterOverview/Events/fixtures/Events.fixture.js
  src/components/ClusterOverview/Events/tests/Events.test.js
  src/components/ClusterOverview/Events/tests/__snapshots__/Events.test.js.snap
  src/components/ClusterOverview/Health/Health.js
  src/components/ClusterOverview/Health/fixtures/Health.fixture.js
  src/components/ClusterOverview/Health/tests/Health.test.js
  src/components/ClusterOverview/Health/tests/HealthBody.test.js
  src/components/ClusterOverview/Health/tests/__snapshots__/Health.test.js.snap
  src/components/ClusterOverview/Health/tests/__snapshots__/HealthBody.test.js.snap
  src/components/ClusterOverview/Inventory/Inventory.js
  src/components/ClusterOverview/Inventory/fixtures/Inventory.fixture.js
  src/components/ClusterOverview/Inventory/tests/Inventory.test.js
  src/components/ClusterOverview/Inventory/tests/__snapshots__/Inventory.test.js.snap
  src/components/ClusterOverview/TopConsumers/TopConsumers.js
  src/components/ClusterOverview/TopConsumers/fixtures/TopConsumers.fixture.js
  src/components/ClusterOverview/TopConsumers/tests/TopConsumers.test.js
  src/components/ClusterOverview/TopConsumers/tests/__snapshots__/TopConsumers.test.js.snap
  src/components/ClusterOverview/Utilization/Utilization.js
  src/components/ClusterOverview/Utilization/fixtures/Utilization.fixture.js
  src/components/ClusterOverview/Utilization/tests/Utilization.test.js
  src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/ClusterOverview/fixtures/ClusterOverview.fixture.js
  src/components/ClusterOverview/index.js
  src/components/ClusterOverview/tests/ClusterOverview.test.js
  src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
Labels: size/XXL

#265 refactor selectors
  src/components/ConfigurationSummary/ConfigurationSummary.js
  src/components/CreateDiskRow/CreateDiskRow.js
  src/components/CreateNicRow/CreateNicRow.js
  src/components/CreateNicRow/tests/CreateNicRow.test.js
  src/components/Details/Description/Description.js
  src/components/Details/Flavor/Flavor.js
  src/components/Details/Flavor/fixtures/Flavor.fixture.js
  src/components/Details/VmDetails/VmDetails.js
  src/components/Details/VmDetails/tests/VmDetails.test.js
  src/components/Details/VmTemplateDetails/VmTemplateDetails.js
  src/components/Details/VmTemplateDetails/tests/VmTemplateDetails.test.js
  src/components/Dialog/BasicMigrationDialog/BasicMigrationDialog.js
  src/components/Dialog/CloneDialog/CloneDialog.js
  src/components/Dialog/CloneDialog/tests/CloneDialog.test.js
  src/components/TemplateSource/TemplateSource.js
  src/components/VmConsoles/VmConsoles.js
  src/components/VmStatus/VmStatus.js
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/providers/VCenterInstances.js
  src/components/Wizard/CreateVmWizard/providers/vmwareActions.js
  src/components/Wizard/CreateVmWizard/tests/BasicSettingsTab.test.js
  src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js
  src/index.js
  src/k8s/clone.js
  src/k8s/migrate.js
  src/k8s/request.js
  src/k8s/tests/clone.test.js
  src/k8s/tests/request.test.js
  src/k8s/vmBuilder.js
  src/selectors/common.js
  src/selectors/dv/index.js
  src/selectors/dv/selectors.js
  src/selectors/host/index.js
  src/selectors/host/selectors.js
  src/selectors/index.js
  src/selectors/internal.js
  src/selectors/pod/index.js
  src/selectors/pod/selectors.js
  src/selectors/pvc/index.js
  src/selectors/pvc/selectors.js
  src/selectors/vm/index.js
  src/selectors/vm/selectors.js
  src/selectors/vmi/index.js
  src/selectors/vmi/selectors.js
  src/selectors/vmi/tests/selectors.test.js
  src/tests/forms_mocks/disk.mock.js
  src/tests/forms_mocks/nic.mock.js
  src/tests/mocks/vm/vm.mock.js
  src/utils/index.js
  src/utils/patches.js
  src/utils/selectors.js
  src/utils/templates.js
  src/utils/tests/templates.test.js
Labels: size/L

#266 v2v: use datavolume instead of PVC
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
Labels: size/XS

#270 Upgrade yarn.lock
  package.json
  src/components/Details/Url/tests/Url.test.js
  src/components/Form/FormFactory.js
  src/components/TemplateSource/tests/TemplateSource.test.js
  src/components/VmStatus/VmStatus.js
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/tests/NetworksTab.test.js
  src/components/Wizard/CreateVmWizard/tests/ResultTab.test.js
  src/components/Wizard/CreateVmWizard/tests/ResultTabRow.test.js
  src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js
  src/components/Wizard/loadingWizardTab.js
  src/cosmos/enzyme.js
  src/k8s/clone.js
  src/utils/templates.js
  yarn.lock
Labels: size/XXL

#275 Bump 0.1.21
  package.json
Labels: size/XS

#277 Fix export of status functions
  src/utils/status/vm/vmStatus.js
Labels: size/S

#278 Upgrade packages
  package.json
  src/components/Form/tests/__snapshots__/FormFactory.test.js.snap
  yarn.lock
Labels: size/XXL

#280 do not export unnecessary functions
  src/utils/status/vm/vmStatus.js
Labels: size/S

#282 Fix cosmos
  src/cosmos/proxies.js
Labels: size/XS

#241 add PVC provision source
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/strings.js
  src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js
  src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
  src/components/Wizard/CreateVmWizard/utils/storageTabUtils.js
  src/constants/index.js
  src/tests/mocks/user_template/index.js
  src/tests/mocks/user_template/pvc.mock.js
  src/utils/templates.js
Labels: size/L

#274 Create labels for elements in vertical forms
  src/components/Dialog/CloneDialog/tests/__snapshots__/CloneDialog.test.js.snap
  src/components/Form/FormFactory.js
  src/components/Form/tests/__snapshots__/FormFactory.test.js.snap
  src/components/VmConsoles/tests/__snapshots__/DesktopViewerSelector.test.js.snap
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/NetworksTab.test.js.snap
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/StorageTab.test.js.snap
Labels: size/M

#281 Capacity: refactor for real data
  src/components/ClusterOverview/Capacity/Capacity.js
  src/components/ClusterOverview/Capacity/fixtures/Capacity.fixture.js
  src/components/ClusterOverview/Capacity/tests/Capacity.test.js
  src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/ClusterOverview/fixtures/ClusterOverview.fixture.js
  src/components/ClusterOverview/index.js
  src/utils/tests/utils.test.js
  src/utils/utils.js
Labels: size/L

#284 Bump 0.1.22
  package.json
Labels: size/XS

#290 Ability to specify if form field labels should be shown
  src/components/CreateDeviceRow/CreateDeviceRow.js
  src/components/CreateDeviceRow/tests/__snapshots__/CreateDeviceRow.test.js.snap
  src/components/Dialog/CloneDialog/tests/__snapshots__/CloneDialog.test.js.snap
  src/components/Form/FormFactory.js
  src/components/Form/tests/__snapshots__/FormFactory.test.js.snap
  src/components/VmConsoles/tests/__snapshots__/DesktopViewerSelector.test.js.snap
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/NetworksTab.test.js.snap
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/StorageTab.test.js.snap
Labels: size/M

#295 Add id to events card body
  src/components/ClusterOverview/Events/Events.js
  src/components/ClusterOverview/Events/tests/__snapshots__/Events.test.js.snap
  src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
Labels: size/XS

#291 Provision source: 's/Image/Cloned Disk/'
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/strings.js
  src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js
  src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
  src/components/Wizard/CreateVmWizard/utils/storageTabUtils.js
  src/constants/index.js
  src/utils/templates.js
Labels: size/M

#297 Fix preferred units when formatting net traffic
  src/utils/utils.js
Labels: size/XS
