Repository kubevirt/web-ui-components, pull requests merged in 2019-02, with the labels that each got.

#203 Move mocked templates to openshift namespace.
  src/k8s/mock_templates/fedora28.mock.js
  src/k8s/mock_templates/rhel-high-p.mock.js
  src/k8s/mock_templates/rhel75.mock.js
  src/k8s/mock_templates/ubuntu1804.mock.js
  src/k8s/mock_templates/windows.mock.js
  src/k8s/tests/request.test.js
  src/models/index.js
  src/utils/tests/templates.test.js
  src/utils/utils.js
Labels: size/M

#205 Compare model against model kind
  src/utils/utils.js
Labels: size/XS

#206 Set template namespace to VM namespace
  src/k8s/request.js
Labels: size/XS

#207 Move templates to openshift ns and use VM namespace when posting to ProcessedTemplates
  src/k8s/mock_templates/fedora28.mock.js
  src/k8s/mock_templates/rhel-high-p.mock.js
  src/k8s/mock_templates/rhel75.mock.js
  src/k8s/mock_templates/ubuntu1804.mock.js
  src/k8s/mock_templates/windows.mock.js
  src/k8s/request.js
  src/k8s/tests/request.test.js
  src/utils/tests/templates.test.js
Labels: size/S

#208 Bump 0.1.17-3
  package.json
Labels: size/XS

#212 Move cloudInit.js to k8s folder
  src/k8s/cloudInit.js
  src/k8s/request.js
  src/k8s/tests/__snapshots__/cloudInit.test.js.snap
  src/k8s/tests/cloudInit.test.js
Labels: size/XS

#213 Extract json patch functions to separate file
  src/utils/index.js
  src/utils/patches.js
  src/utils/tests/patches.test.js
  src/utils/utils.js
Labels: size/XL

#214 Add template name and namespace to VM labels.
  src/components/Details/VmDetails/fixtures/VmDetails.fixture.js
  src/constants/index.js
  src/k8s/request.js
  src/k8s/tests/request.test.js
  src/tests/mocks/user_template/container-cloud.mock.js
  src/tests/mocks/user_template/container-multus.mock.js
  src/tests/mocks/user_template/container.mock.js
  src/tests/mocks/user_template/pxe-dv.mock.js
  src/tests/mocks/user_template/pxe-pvc.mock.js
  src/tests/mocks/user_template/pxe.mock.js
  src/tests/mocks/user_template/url-flavor.mock.js
  src/tests/mocks/user_template/url-nonetwork.mock.js
  src/tests/mocks/user_template/url.mock.js
  src/utils/selectors.js
  src/utils/tests/templates.test.js
Labels: size/L

#209 Use dataVolumeTemplates instead of creating PVC/DV objects.
  src/components/ConfigurationSummary/ConfigurationSummary.js
  src/components/ConfigurationSummary/fixtures/ConfigurationSummary.fixture.js
  src/components/ConfigurationSummary/tests/__snapshots__/ConfigurationSummary.test.js.snap
  src/components/Dialog/CloneDialog/CloneDialog.js
  src/components/Dialog/CloneDialog/tests/CloneDialog.test.js
  src/components/TemplateSource/TemplateSource.js
  src/components/TemplateSource/fixtures/TemplateSource.fixture.js
  src/components/TemplateSource/tests/TemplateSource.test.js
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/ResultTab.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/constants.js
  src/components/Wizard/CreateVmWizard/fixtures/CreateVmWizard.fixture.js
  src/components/Wizard/CreateVmWizard/fixtures/ResultTab.fixture.js
  src/components/Wizard/CreateVmWizard/tests/BasicSettingsTab.test.js
  src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js
  src/components/Wizard/CreateVmWizard/tests/ResultTab.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/ResultTab.test.js.snap
  src/k8s/clone.js
  src/k8s/request.js
  src/k8s/tests/clone.test.js
  src/k8s/tests/migrate.test.js
  src/k8s/tests/request.test.js
  src/k8s/vmBuilder.js
  src/tests/forms_mocks/disk.mock.js
  src/tests/k8s.js
  src/tests/mocks/persistentVolumeClaim/index.js
  src/tests/mocks/user_template/url.mock.js
  src/tests/mocks/vm/vm.mock.js
  src/utils/selectors.js
  src/utils/templates.js
  src/utils/tests/templates.test.js
  src/utils/utils.js
Labels: size/XXL

#219 Extract form types to constants
  src/components/CreateDeviceRow/CreateDeviceRow.js
  src/components/CreateDiskRow/CreateDiskRow.js
  src/components/CreateNicRow/CreateNicRow.js
  src/components/Details/Description/Description.js
  src/components/Details/Flavor/Flavor.js
  src/components/Dialog/CloneDialog/CloneDialog.js
  src/components/Form/FormFactory.js
  src/components/Form/constants.js
  src/components/Form/index.js
  src/components/InlineEdit/InlineEdit.js
  src/components/Table/EditableDraggableTable.js
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
Labels: size/L

#222 Dropdown: choices are optional
  src/components/Form/Dropdown.js
Labels: size/XS

#223 FormFactory: pass extraProps to CustomComponent and onChange hook
  src/components/Form/FormFactory.js
Labels: size/S

#221 Add SecretsModel
  src/models/index.js
Labels: size/S

#225 StorageTab: fix for empty list
  src/components/Wizard/CreateVmWizard/StorageTab.js
Labels: size/XS

#228 expose addPrefixToPatch
  src/components/Details/VmTemplateDetails/VmTemplateDetails.js
  src/utils/patches.js
Labels: size/S

#224 models: Add ServiceModel and RouteModel
  src/models/index.js
Labels: size/S

#227 Form: enable password input-text components
  src/components/Form/FormFactory.js
  src/components/Form/Text.js
  src/components/Form/constants.js
  src/components/Form/fixtures/FormFactory.fixture.js
  src/components/Form/tests/__snapshots__/FormFactory.test.js.snap
Labels: size/L

#226 Dropdown: overflow for long values
  sass/_components.scss
  sass/components/Form/dropdown.scss
  sass/patternfly-tweaks/dropdown.scss
  src/components/Form/Dropdown.js
  src/components/Form/fixtures/Dropdown.fixture.js
  src/components/Form/tests/Dropdown.test.js
  src/components/Form/tests/__snapshots__/Dropdown.test.js.snap
  src/components/Form/tests/__snapshots__/FormFactory.test.js.snap
Labels: size/L

#232 add units for disk size in VM disk page
  sass/components/Form/form-group.scss
  src/components/CreateDiskRow/CreateDiskRow.js
  src/components/CreateDiskRow/fixtures/CreateDiskRow.fixture.js
  src/components/CreateDiskRow/tests/__snapshots__/CreateDiskRow.test.js.snap
  src/components/Dialog/CloneDialog/tests/CloneDialog.test.js
  src/components/Form/Checkbox.js
  src/components/Form/Dropdown.js
  src/components/Form/FormFactory.js
  src/components/Form/Integer.js
  src/components/Form/Text.js
  src/components/Form/tests/__snapshots__/FormFactory.test.js.snap
  src/components/Wizard/CreateVmWizard/strings.js
  src/components/Wizard/CreateVmWizard/tests/NetworksTab.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/StorageTab.test.js.snap
Labels: size/L

#231 fix workload help message
  src/components/Wizard/CreateVmWizard/strings.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
Labels: size/XS

#234 Improve Clone Dialog style
  sass/_components.scss
  sass/components/Dialog/clone-dialog.scss
  src/components/Dialog/CloneDialog/CloneDialog.js
  src/components/Dialog/CloneDialog/tests/__snapshots__/CloneDialog.test.js.snap
Labels: size/L

#237 prevent template rootdisk (the first bootable disk) from deletion when creating VMs
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
Labels: size/S

#236 Do not convert disk size to GB
  src/components/ConfigurationSummary/ConfigurationSummary.js
  src/components/ConfigurationSummary/fixtures/ConfigurationSummary.fixture.js
  src/components/ConfigurationSummary/tests/__snapshots__/ConfigurationSummary.test.js.snap
  src/components/Dialog/CloneDialog/CloneDialog.js
Labels: size/M

#235 Delete VM annotations and firmware fields when cloning
  src/k8s/clone.js
Labels: size/S

#210 V2V
  sass/components/Wizard/create-vm-wizard.scss
  src/components/Dialog/BasicMigrationDialog/fixtures/BasicMigrationDialog.fixture.js
  src/components/Dialog/BasicMigrationDialog/tests/BasicMigrationDialog.test.js
  src/components/Dialog/CloneDialog/fixtures/CloneDialog.fixture.js
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/constants.js
  src/components/Wizard/CreateVmWizard/fixtures/BasicSettingsTab.fixture.js
  src/components/Wizard/CreateVmWizard/fixtures/CreateVmWizard.fixture.js
  src/components/Wizard/CreateVmWizard/providers/VCenterInstances.js
  src/components/Wizard/CreateVmWizard/providers/VCenterVms.js
  src/components/Wizard/CreateVmWizard/providers/VMWarePasswordAndCheck.js
  src/components/Wizard/CreateVmWizard/providers/VMWareProviderStatus.js
  src/components/Wizard/CreateVmWizard/providers/fixtures/VCenterInstances.fixture.js
  src/components/Wizard/CreateVmWizard/providers/fixtures/VCenterVms.fixture.js
  src/components/Wizard/CreateVmWizard/providers/fixtures/VMWarePasswordAndCheck.fixture.js
  src/components/Wizard/CreateVmWizard/providers/fixtures/VMWareProviderStatus.fixture.js
  src/components/Wizard/CreateVmWizard/providers/index.js
  src/components/Wizard/CreateVmWizard/providers/tests/VCenterInstances.test.js
  src/components/Wizard/CreateVmWizard/providers/tests/VCenterVms.test.js
  src/components/Wizard/CreateVmWizard/providers/tests/VMWarePasswordAndCheck.test.js
  src/components/Wizard/CreateVmWizard/providers/tests/VMWareProviderStatus.test.js
  src/components/Wizard/CreateVmWizard/providers/tests/__snapshots__/VCenterInstances.test.js.snap
  src/components/Wizard/CreateVmWizard/providers/tests/__snapshots__/VCenterVms.test.js.snap
  src/components/Wizard/CreateVmWizard/providers/tests/__snapshots__/VMWarePasswordAndCheck.test.js.snap
  src/components/Wizard/CreateVmWizard/providers/tests/__snapshots__/VMWareProviderStatus.test.js.snap
  src/components/Wizard/CreateVmWizard/providers/tests/v2vvmwareController.test.js
  src/components/Wizard/CreateVmWizard/providers/tests/vmware.test.js
  src/components/Wizard/CreateVmWizard/providers/tests/vmwareActions.test.js
  src/components/Wizard/CreateVmWizard/providers/tests/vmwareProviderPod.test.js
  src/components/Wizard/CreateVmWizard/providers/v2vvmwareController.js
  src/components/Wizard/CreateVmWizard/providers/vmware.js
  src/components/Wizard/CreateVmWizard/providers/vmwareActions.js
  src/components/Wizard/CreateVmWizard/providers/vmwareProviderPod.js
  src/components/Wizard/CreateVmWizard/strings.js
  src/components/Wizard/CreateVmWizard/tests/BasicSettingsTab.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
  src/constants/index.js
  src/k8s/import.js
  src/k8s/request.js
  src/k8s/selectors.js
  src/k8s/tests/request.test.js
  src/models/index.js
  src/tests/forms_mocks/basicSettings.mock.js
  src/tests/k8s.js
  src/utils/strings.js
  src/utils/tests/validation.test.js
  src/utils/validations.js
Labels: size/XXL

#229 shorten URL in VmTemplateDetail and refactor TemplateSource
  src/components/Details/Url/Url.js
  src/components/Details/Url/fixtures/Url.fixture.js
  src/components/Details/Url/index.js
  src/components/Details/Url/tests/Url.test.js
  src/components/Details/Url/tests/__snapshots__/Url.test.js.snap
  src/components/Details/VmTemplateDetails/tests/__snapshots__/VmTemplateDetails.test.js.snap
  src/components/TemplateSource/TemplateSource.js
  src/components/TemplateSource/fixtures/TemplateSource.fixture.js
  src/components/TemplateSource/tests/TemplateSource.test.js
  src/components/TemplateSource/tests/__snapshots__/TemplateSource.test.js.snap
  src/tests/mocks/user_template/url-flavor.mock.js
  src/tests/mocks/user_template/url-nonetwork.mock.js
  src/tests/mocks/user_template/url.mock.js
  src/utils/tests/templates.test.js
  src/utils/utils.js
  src/utils/validations.js
Labels: size/L

#233 VmCreateDialog: display JSONs on error in ResultsTab
  sass/components/Wizard/create-vm-wizard.scss
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/ResultTab.js
  src/components/Wizard/CreateVmWizard/ResultTabRow.js
  src/components/Wizard/CreateVmWizard/fixtures/ResultTab.fixture.js
  src/components/Wizard/CreateVmWizard/fixtures/ResultTabRow.fixture.js
  src/components/Wizard/CreateVmWizard/strings.js
  src/components/Wizard/CreateVmWizard/tests/ResultTab.test.js
  src/components/Wizard/CreateVmWizard/tests/ResultTabRow.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/ResultTab.test.js.snap
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/ResultTabRow.test.js.snap
  src/k8s/request.js
Labels: size/L

#218 Add L2 Network RDP connection
  sass/_components.scss
  sass/components/VmConsoles/desktop-viewer-selector.scss
  sass/components/VmConsoles/vm-consoles.scss
  src/components/VmConsoles/DesktopViewerSelector.js
  src/components/VmConsoles/VmConsoles.js
  src/components/VmConsoles/constants.js
  src/components/VmConsoles/fixtures/DesktopViewerSelector.fixture.js
  src/components/VmConsoles/strings.js
  src/components/VmConsoles/tests/DesktopViewerSelector.test.js
  src/components/VmConsoles/tests/__snapshots__/DesktopViewerSelector.test.js.snap
  src/components/VmConsoles/tests/__snapshots__/VmConsoles.test.js.snap
  src/utils/selectors.js
Labels: size/L
