Repository kubevirt/web-ui-components, pull requests merged in 2019-11, with the labels that each got.

#572 fix(plugins): add spread operator plugin for edge support
  config/babel.config.js
  package.json
  yarn.lock
Labels: dco-signoff: no, size/S

#573 fix(plugins): add spread operator plugin for edge support (#572)
  config/babel.config.js
  package.json
  yarn.lock
Labels: dco-signoff: yes, size/S

#574 Bump 0.1.44-2
  package.json
Labels: dco-signoff: yes, size/XS

#575 Bump 0.1.50
  package.json
Labels: dco-signoff: yes, size/XS

#576 add default value to getsettings
  src/k8s/request.js
Labels: dco-signoff: yes, size/XS
