Repository kubevirt/web-ui-components, pull requests merged in 2019-07, with the labels that each got.

#506 Fix Firehose propType
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
Labels: size/XS

#507 Configure V2V via ConfigMap
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/requestedResources.js
  src/config/index.js
  src/k8s/objects/v2v/vmware/conversionPod.js
  src/k8s/objects/v2v/vmware/vmWareDeployment.js
  src/k8s/request.js
  src/k8s/requests/v2v/constants.js
  src/k8s/requests/v2v/importVmware.js
  src/k8s/requests/v2v/startV2VvmwareController.js
  src/selectors/v2v/selectors.js
  src/tests/k8s.js
Labels: size/L

#508 Upgrade lodash to 4.17.14
  yarn.lock
Labels: size/XS

#509 Bump 0.1.37
  package.json
Labels: size/XS

#511 Upgrade js-yaml dependency
  yarn.lock
Labels: size/S

#517 Upgrade js-yaml and lodash
  yarn.lock
Labels: size/S

#516 Remove dot character from DNS-1123 validation
  src/utils/tests/validation.test.js
  src/utils/validations.js
Labels: size/XS

#518 Bump 0.1.38
  package.json
Labels: size/XS

#519 Create VM Wizard: conditionally rendered Import provision source
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/initialState/vmSettingsTabInitialState.js
Labels: size/S

#520 Bump 0.1.39
  package.json
Labels: size/XS

#521 CloneDialog: support non-admin users
  src/components/Dialog/CloneDialog/CloneDialog.js
  src/components/Dialog/CloneDialog/fixtures/CloneDialog.fixture.js
  src/components/Dialog/CloneDialog/index.js
  src/components/Dialog/CloneDialog/tests/CloneDialog.test.js
  src/components/Dialog/CloneDialog/tests/__snapshots__/CloneDialog.test.js.snap
Labels: size/L

#522 Bump 0.1.34-10
  package.json
Labels: size/XS

#523 fix VM Template name validation
  src/components/Dialog/CloneDialog/CloneDialog.js
  src/components/Wizard/CreateVmWizard/constants.js
  src/components/Wizard/CreateVmWizard/validations/vmSettingsTabValidation.js
  src/utils/strings.js
  src/utils/tests/validation.test.js
  src/utils/validations.js
Labels: size/M

#525 deprecate baseTemplates to simplify loading and OS list flicker
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/fixtures/CreateVmWizard.fixture.js
  src/components/Wizard/CreateVmWizard/stateUpdate/vmSettingsTabStateUpdate.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap
  src/utils/templates.js
  src/utils/tests/templates.test.js
Labels: size/M

#526 validate template sources with missing DataVolume
  src/components/TemplateSource/TemplateSource.js
  src/components/Wizard/CreateVmWizard/constants.js
  src/components/Wizard/CreateVmWizard/stateUpdate/vmSettingsTabStateUpdate.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap
  src/components/Wizard/CreateVmWizard/validations/vmSettingsTabValidation.js
  src/constants/index.js
  src/utils/templates.js
  src/utils/validations.js
Labels: size/M

#529 v2v: change "VM to import" to "VM or Template"
  src/components/Wizard/CreateVmWizard/initialState/providers/vmWareInitialState.js
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/tests/__snapshots__/VMWareImportProvider.test.js.snap
  src/components/Wizard/CreateVmWizard/strings.js
Labels: size/M

#530 v2v: generate shorter vCenter instance secret name
  src/k8s/requests/v2v/tests/utils.test.js
  src/k8s/requests/v2v/utils.js
Labels: size/M

#524 make DNS1123 validation more verbose
  src/components/Form/FormFactory.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js
  src/utils/grammar.js
  src/utils/strings.js
  src/utils/tests/validation.test.js
  src/utils/validations.js
Labels: size/L

#528 Use SC defaults for DV creation
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/constants/index.js
  src/k8s/clone.js
  src/k8s/request.js
  src/k8s/vmBuilder.js
  src/selectors/configmap/index.js
  src/selectors/configmap/sc-defaults.js
  src/selectors/dv/selectors.js
  src/selectors/index.js
  src/selectors/pvc/selectors.js
Labels: size/L
