Repository kubevirt/web-ui-components, pull requests merged in 2019-01, with the labels that each got.

#135 Create VmDetails component
  sass/_components.scss
  sass/components/_VmDetails.scss
  src/components/CreateDiskRow/fixtures/CreateDiskRow.fixture.js
  src/components/Details/VmDetails/VmDetails.js
  src/components/Details/VmDetails/fixtures/VmDetails.fixture.js
  src/components/Details/VmDetails/index.js
  src/components/Details/VmDetails/tests/VmDetails.test.js
  src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap
  src/index.js
  src/k8s/mock_pod/cloudInitTestPod.pod.js
  src/k8s/mock_vm/cloudInitTestVm.vm.js
  src/k8s/mock_vmi/cloudInitTestVmi.vmi.js
  src/utils/selectors.js
Labels: size/XXL

#153 Vm Details cleanup
  sass/components/_VmDetails.scss
  src/components/Details/VmDetails/VmDetails.js
  src/components/Details/VmDetails/fixtures/VmDetails.fixture.js
  src/components/Details/VmDetails/tests/VmDetails.test.js
  src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap
  src/utils/selectors.js
  src/utils/tests/selectors.test.js
Labels: size/XXL

#154 Update react-console to 1.10.5
  package.json
  src/components/VmConsoles/tests/__snapshots__/VmConsoles.test.js.snap
  yarn.lock
Labels: size/S

#158 fix isBeingMigrated function
  src/components/VmStatus/fixtures/VmStatus.fixture.js
  src/components/VmStatus/getVmStatus.js
Labels: size/S

#127 Add DesktopViewer to VmConsoles
  sass/components/_VmConsoles.scss
  src/components/VmConsoles/VmConsoles.js
  src/components/VmConsoles/fixtures/VmConsoles.fixture.js
  src/components/VmConsoles/tests/VmConsoles.test.js
  src/components/VmConsoles/tests/__snapshots__/VmConsoles.test.js.snap
  src/constants/index.js
  src/k8s/request.js
  src/utils/selectors.js
Labels: size/L

#163 Upgrade @patternfly/react-console to 1.10.8
  yarn.lock
Labels: size/XS

#164 Add help icons to Create Vm/BasicSettings tab.
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/strings.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
Labels: size/M

#156 Add edit functionality to Vm Details overview
  src/components/Details/Description/Description.js
  src/components/Details/Description/fixtures/Description.fixture.js
  src/components/Details/Description/index.js
  src/components/Details/Description/tests/Description.test.js
  src/components/Details/Description/tests/__snapshots__/Description.test.js.snap
  src/components/Details/Flavor/Flavor.js
  src/components/Details/Flavor/fixtures/Flavor.fixture.js
  src/components/Details/Flavor/index.js
  src/components/Details/Flavor/tests/Flavor.test.js
  src/components/Details/Flavor/tests/__snapshots__/Flavor.test.js.snap
  src/components/Details/VmDetails/VmDetails.js
  src/components/Details/VmDetails/fixtures/VmDetails.fixture.js
  src/components/Details/VmDetails/tests/VmDetails.test.js
  src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap
  src/components/Dialog/BasicMigrationDialog/fixtures/BasicMigrationDialog.fixture.js
  src/components/Dialog/BasicMigrationDialog/tests/BasicMigrationDialog.test.js
  src/components/Form/Dropdown.js
  src/components/Form/FormFactory.js
  src/components/Form/tests/__snapshots__/Dropdown.test.js.snap
  src/components/Form/tests/__snapshots__/FormFactory.test.js.snap
  src/components/Form/tests/utils.test.js
  src/components/Form/utils.js
  src/components/InlineEdit/InlineEdit.js
  src/components/InlineEdit/fixtures/InlineEdit.fixture.js
  src/components/InlineEdit/index.js
  src/components/InlineEdit/tests/InlineEdit.test.js
  src/components/InlineEdit/tests/__snapshots__/InlineEdit.test.js.snap
  src/components/Loading/Loading.js
  src/constants/index.js
  src/k8s/mock_pod/cloudInitTestPod.mock.js
  src/k8s/mock_vm/cloudInitTestVm.mock.js
  src/k8s/mock_vmi/blue.mock.js
  src/k8s/mock_vmi/cloudInitTestVmi.mock.js
  src/k8s/tests/migrate.test.js
  src/utils/selectors.js
  src/utils/tests/selectors.test.js
  src/utils/tests/utils.test.js
  src/utils/utils.js
Labels: size/XXL

#152 add custom cloud-init script to Create VM Dialog
  sass/components/Wizard/create-vm-wizard.scss
  src/components/Form/FormFactory.js
  src/components/Form/TextArea.js
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/constants.js
  src/components/Wizard/CreateVmWizard/tests/BasicSettingsTab.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
  src/k8s/request.js
  src/k8s/request/cloudInit.js
  src/k8s/request/tests/__snapshots__/cloudInit.test.js.snap
  src/k8s/request/tests/cloudInit.test.js
  src/k8s/tests/request.test.js
  src/utils/selectors.js
Labels: size/L

#166 Add 'dev' script to do a development build
  docs/DevGuide.md
  package.json
Labels: size/S

#167 Bump 0.1.15
  package.json
Labels: size/XS

#169 Do not allow uppercase letters in DNS1123 validation.
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js
  src/utils/strings.js
  src/utils/tests/validation.test.js
  src/utils/validations.js
Labels: size/M

#170 Show full OS names.
  src/components/Details/VmDetails/VmDetails.js
  src/components/Form/Dropdown.js
  src/components/Form/FormFactory.js
  src/components/Form/tests/__snapshots__/Dropdown.test.js.snap
  src/components/Form/tests/__snapshots__/FormFactory.test.js.snap
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/fixtures/BasicSettingsTab.fixture.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
  src/constants/index.js
  src/k8s/mock_templates/fedora28.mock.js
  src/k8s/mock_templates/rhel-high-p.mock.js
  src/k8s/mock_templates/rhel75.mock.js
  src/k8s/mock_templates/ubuntu1804.mock.js
  src/k8s/mock_templates/windows.mock.js
  src/k8s/mock_user_templates/container-cloud.mock.js
  src/k8s/mock_user_templates/container-multus.mock.js
  src/k8s/mock_user_templates/container.mock.js
  src/k8s/mock_user_templates/pxe-dv.mock.js
  src/k8s/mock_user_templates/pxe-pvc.mock.js
  src/k8s/mock_user_templates/pxe.mock.js
  src/k8s/mock_user_templates/url-flavor.mock.js
  src/k8s/mock_user_templates/url-nonetwork.mock.js
  src/k8s/mock_user_templates/url.mock.js
  src/k8s/request.js
  src/k8s/selectors.js
  src/k8s/tests/request.test.js
  src/k8s/tests/selectors.test.js
  src/utils/selectors.js
Labels: size/L

#172 fix default disk
  src/k8s/request.js
Labels: size/S

#171 Fix VM Details form validity detection
  src/components/Details/Flavor/Flavor.js
  src/components/Details/Flavor/tests/__snapshots__/Flavor.test.js.snap
  src/components/Details/VmDetails/VmDetails.js
  src/components/Details/VmDetails/fixtures/VmDetails.fixture.js
  src/components/Details/VmDetails/tests/VmDetails.test.js
  src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap
  src/utils/templates.js
  src/utils/tests/templates.test.js
Labels: size/L

#175 Use nic{id} instead of eth{id} for NIC names
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/tests/NetworksTab.test.js
Labels: size/XS

#165 link to pod when a container is in a CrashLoopBackOff
  src/components/Details/VmDetails/VmDetails.js
  src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap
  src/components/VmStatus/VmStatus.js
  src/components/VmStatus/fixtures/VmStatus.fixture.js
  src/components/VmStatus/getVmStatus.js
  src/components/VmStatus/index.js
  src/components/VmStatus/tests/VmStatus.test.js
  src/components/VmStatus/tests/__snapshots__/VmStatus.test.js.snap
  src/constants/index.js
  src/utils/selectors.js
Labels: size/XL

#173 Disable VM editing if VM is running
  sass/components/VmDetails/vm-details.scss
  src/components/Details/VmDetails/VmDetails.js
  src/components/Details/VmDetails/fixtures/VmDetails.fixture.js
  src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap
Labels: size/M

#179 Improve URL provision source help text.
  src/components/Wizard/CreateVmWizard/strings.js
Labels: size/XS

#177 Table renderConfig is now function, not static declaration.
  src/components/CreateNicRow/CreateNicRow.js
  src/components/CreateNicRow/tests/__snapshots__/CreateNicRow.test.js.snap
  src/components/Table/EditableDraggableTable.js
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/NetworksTab.test.js.snap
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/StorageTab.test.js.snap
  src/utils/tests/utils.test.js
  src/utils/utils.js
Labels: size/L

#178 FormFactory handles form validation
  src/components/CreateDeviceRow/CreateDeviceRow.js
  src/components/CreateDeviceRow/fixtures/CreateDeviceRow.fixture.js
  src/components/CreateDeviceRow/index.js
  src/components/CreateDeviceRow/tests/CreateDeviceRow.test.js
  src/components/CreateDeviceRow/tests/__snapshots__/CreateDeviceRow.test.js.snap
  src/components/CreateDiskRow/CreateDiskRow.js
  src/components/CreateDiskRow/tests/__snapshots__/CreateDiskRow.test.js.snap
  src/components/CreateNicRow/CreateNicRow.js
  src/components/CreateNicRow/tests/__snapshots__/CreateNicRow.test.js.snap
  src/components/Details/Description/Description.js
  src/components/Details/Flavor/Flavor.js
  src/components/Form/FormFactory.js
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
Labels: size/L

#180 volumeName from disk spec is removed. apiVersion changed to v1alpha3.
  src/constants/index.js
  src/k8s/mock_templates/fedora28.mock.js
  src/k8s/mock_templates/rhel-high-p.mock.js
  src/k8s/mock_templates/rhel75.mock.js
  src/k8s/mock_templates/ubuntu1804.mock.js
  src/k8s/mock_templates/windows.mock.js
  src/k8s/mock_user_templates/container-cloud.mock.js
  src/k8s/mock_user_templates/container-multus.mock.js
  src/k8s/mock_user_templates/container.mock.js
  src/k8s/mock_user_templates/pxe-dv.mock.js
  src/k8s/mock_user_templates/pxe-pvc.mock.js
  src/k8s/mock_user_templates/pxe.mock.js
  src/k8s/mock_user_templates/url-flavor.mock.js
  src/k8s/mock_user_templates/url-nonetwork.mock.js
  src/k8s/mock_user_templates/url.mock.js
  src/k8s/mock_vm/cloudInitTestVm.mock.js
  src/k8s/mock_vmi/blue.mock.js
  src/k8s/mock_vmi/cloudInitTestVmi.mock.js
  src/k8s/request.js
  src/k8s/request/tests/__snapshots__/cloudInit.test.js.snap
  src/k8s/tests/request.test.js
  src/models/index.js
  src/utils/selectors.js
  src/utils/templates.js
  src/utils/tests/utils.test.js
  src/utils/utils.js
Labels: do-not-merge/hold, size/L

#181 add url and container validations
  src/components/Wizard/CreateVmWizard/BasicSettingsTab.js
  src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/BasicSettingsTab.test.js.snap
  src/utils/strings.js
  src/utils/tests/validation.test.js
  src/utils/validations.js
Labels: size/L

#182 VmConsoles: Connection is kept by default when switching console types
  src/components/VmConsoles/VmConsoles.js
  src/components/VmConsoles/tests/__snapshots__/VmConsoles.test.js.snap
Labels: size/XS

#184 Clear IP addresses & FQDN when VM is off
  src/components/Details/VmDetails/VmDetails.js
  src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap
  src/utils/selectors.js
Labels: size/S

#187 use lodash trim for better browser support
  src/utils/validations.js
Labels: size/S

#189 Fix VM details issues
  src/components/Details/VmDetails/VmDetails.js
  src/components/Details/VmDetails/fixtures/VmDetails.fixture.js
  src/components/Details/VmDetails/tests/VmDetails.test.js
  src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap
  src/utils/selectors.js
  src/utils/tests/selectors.test.js
Labels: size/M

#190 Improve reading and cleaning storages and networks on user template c…
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js
Labels: size/L

#192 Bump 0.1.17
  package.json
Labels: size/XS

#195 Rename NIC/Disk Name to just Name
  src/components/CreateNicRow/CreateNicRow.js
  src/components/CreateNicRow/tests/__snapshots__/CreateNicRow.test.js.snap
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/strings.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/NetworksTab.test.js.snap
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/StorageTab.test.js.snap
Labels: size/S

#200 Refactor: move getResource() to web-ui-components
  src/utils/utils.js
Labels: size/S

#198 Add BEM block to VmStatus component
  docs/DevGuide.md
  src/components/VmStatus/VmStatus.js
  src/components/VmStatus/tests/__snapshots__/VmStatus.test.js.snap
Labels: size/M

#201 Bump 0.1.18
  package.json
Labels: size/XS

#202 Bump 0.1.17-2
  package.json
Labels: size/XS
