Repository kubevirt/web-ui-components, pull requests merged in 2019-08, with the labels that each got.

#531 v2v: fix VM loading when race condition occurs
  src/components/Wizard/CreateVmWizard/providers/VMwareImportProvider/VMWareImportProvider.js
  src/components/Wizard/CreateVmWizard/validations/providers/vmWareValidation.js
Labels: size/S

#532 v2v: move v2v-vmware ConfigMap to kubevirt-hyperconverged namespace
  src/k8s/requests/v2v/constants.js
  src/k8s/requests/v2v/startV2VvmwareController.js
Labels: size/S

#533 v2v: Wait for ServiceAccount before creating conversion pod
  src/components/Wizard/CreateVmWizard/stateUpdate/providers/vmWareStateUpdate.js
  src/k8s/requests/v2v/constants.js
  src/k8s/requests/v2v/importVmware.js
  src/selectors/serviceaccount/index.js
  src/selectors/serviceaccount/serviceaccount.js
  src/utils/utils.js
Labels: size/M

#527 Add MAC address validation to Create VM wizard
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/strings.js
  src/components/Wizard/CreateVmWizard/tests/NetworksTab.test.js
  src/utils/strings.js
  src/utils/tests/validation.test.js
  src/utils/validations.js
Labels: size/L

#534 Deploy VDDK as side-car container
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/constants.js
  src/components/Wizard/CreateVmWizard/stateUpdate/providers/prefillVmStateUpdate.js
  src/k8s/objects/v2v/vmware/conversionPod.js
  src/k8s/request.js
  src/k8s/requests/v2v/constants.js
  src/k8s/requests/v2v/importVmware.js
  src/selectors/v2v/selectors.js
Labels: size/M

#535 Bump 0.1.40
  package.json
Labels: size/XS

#536 add babel esm and umd exports
  config/babel.config.js
  config/eslint.browser.js
  config/jest.config.js
  config/jest.transform.babel.js
  package.json
  src/components/BareMetalHosts/tests/BaremetalHostRole.test.js
  src/components/BareMetalHosts/tests/BaremetalHostStatus.test.js
  src/components/CancelAcceptButtons/tests/CancelAcceptButtons.test.js
  src/components/ClusterOverview/fixtures/ClusterOverview.fixture.js
  src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
  src/components/ConfigurationSummary/fixtures/ConfigurationSummary.fixture.js
  src/components/ConfigurationSummary/tests/ConfigurationSummary.test.js
  src/components/CreateDeviceRow/fixtures/CreateDeviceRow.fixture.js
  src/components/CreateDeviceRow/tests/CreateDeviceRow.test.js
  src/components/CreateNicRow/tests/CreateNicRow.test.js
  src/components/Details/Description/fixtures/Description.fixture.js
  src/components/Details/Description/tests/Description.test.js
  src/components/Details/Flavor/fixtures/Flavor.fixture.js
  src/components/Details/Flavor/tests/Flavor.test.js
  src/components/Details/Url/tests/Url.test.js
  src/components/Dialog/BasicMigrationDialog/tests/BasicMigrationDialog.test.js
  src/components/Dialog/CloneDialog/fixtures/CloneDialog.fixture.js
  src/components/Dialog/CloneDialog/tests/CloneDialog.test.js
  src/components/InlineEdit/tests/InlineEdit.test.js
  src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
  src/utils/status/vm/vmStatus.js
  yarn.lock
Labels: size/XXL
