Repository kubevirt/web-ui-components, pull requests merged in 2019-05, with the labels that each got.

#426 remove dirty substring from openshift version
  src/selectors/prometheus/cluster.js
Labels: size/XS

#429 package.json: use compatible react versions with web-ui
  package.json
  src/jest/setupTest.js
  yarn.lock
Labels: size/L

#425 Update top consumers description and units
  src/components/ClusterOverview/TopConsumers/TopConsumers.js
  src/components/ClusterOverview/TopConsumers/strings.js
  src/components/ClusterOverview/TopConsumers/tests/__snapshots__/TopConsumers.test.js.snap
  src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
Labels: size/M

#434 Fix v2v image name
  src/config/index.js
Labels: size/XS

#433 Fix v2v image name
  src/config/index.js
Labels: size/XS

#430 Delete new row when cancel is clicked
  src/components/Table/EditableDraggableTable.js
  src/components/Table/TableFactory.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js
  src/components/Wizard/CreateVmWizard/tests/NetworksTab.test.js
  src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js
Labels: size/L

#437 Use PureComponents for dashboard
  src/components/ClusterOverview/Alerts/Alerts.js
  src/components/ClusterOverview/Capacity/Capacity.js
  src/components/ClusterOverview/ClusterOverview.js
  src/components/ClusterOverview/Compliance/Compliance.js
  src/components/ClusterOverview/Details/Details.js
  src/components/ClusterOverview/Events/Events.js
  src/components/ClusterOverview/Health/Health.js
  src/components/ClusterOverview/TopConsumers/TopConsumers.js
  src/components/ClusterOverview/Utilization/Utilization.js
  src/components/Dashboard/Alert/AlertItem.js
  src/components/Dashboard/Capacity/CapacityItem.js
  src/components/Dashboard/DashboardCard/DashboardCard.js
  src/components/Dashboard/DashboardCard/DashboardCardBody.js
  src/components/Dashboard/DashboardCard/DashboardCardHeader.js
  src/components/Dashboard/DashboardCard/DashboardCardTitle.js
  src/components/Dashboard/DashboardCard/DashboardCardTitleHelp.js
  src/components/Dashboard/DashboardCard/DashboardCardTitleSeeAll.js
  src/components/Dashboard/Details/DetailItem.js
  src/components/Dashboard/Health/HealthBody.js
  src/components/Dashboard/Health/HealthItem.js
  src/components/Dashboard/Inventory/InventoryRow.js
  src/components/Dashboard/TopConsumers/ConsumerItem.js
Labels: size/XXL

#431 Add more fixtures and snapshot tests for dashboard
  src/components/Dashboard/Alert/tests/AlertItem.test.js
  src/components/Dashboard/Alert/tests/__snapshots__/AlertItem.test.js.snap
  src/components/Dashboard/Capacity/fixtures/CapacityItem.fixture.js
  src/components/Dashboard/Capacity/tests/CapacityItem.test.js
  src/components/Dashboard/Capacity/tests/__snapshots__/CapacityItem.test.js.snap
  src/components/Dashboard/DashboardCard/fixtures/DashboardCardBody.fixture.js
  src/components/Dashboard/DashboardCard/tests/DashboardCardBody.test.js
  src/components/Dashboard/DashboardCard/tests/DashboardCardTitleSeeAll.test.js
  src/components/Dashboard/DashboardCard/tests/__snapshots__/DashboardCardBody.test.js.snap
  src/components/Dashboard/DashboardCard/tests/__snapshots__/DashboardCardTitleSeeAll.test.js.snap
  src/components/Dashboard/Details/fixtures/DetailItem.fixture.js
  src/components/Dashboard/Details/tests/DetailItem.test.js
  src/components/Dashboard/Details/tests/__snapshots__/DetailItem.test.js.snap
  src/components/Dashboard/Health/fixtures/HealthItem.fixture.js
  src/components/Dashboard/Health/tests/HealthItem.test.js
  src/components/Dashboard/Health/tests/__snapshots__/HealthBody.test.js.snap
  src/components/Dashboard/Health/tests/__snapshots__/HealthItem.test.js.snap
  src/components/Dashboard/Inventory/fixtures/InventoryRow.fixture.js
  src/components/Dashboard/Inventory/tests/InventoryRow.test.js
  src/components/Dashboard/Inventory/tests/__snapshots__/InventoryRow.test.js.snap
  src/components/Dashboard/SubsystemHealth/fixtures/SubsystemHealth.fixture.js
  src/components/Dashboard/SubsystemHealth/tests/SubsystemHealth.test.js
  src/components/Dashboard/SubsystemHealth/tests/__snapshots__/SubsystemHealth.test.js.snap
  src/components/Dashboard/TopConsumers/fixtures/ConsumersResults.fixture.js
  src/components/Dashboard/TopConsumers/tests/ConsumersResults.test.js
  src/components/Dashboard/TopConsumers/tests/__snapshots__/ConsumersResults.test.js.snap
  src/components/Dashboard/Utilization/fixtures/UtilizationItem.fixture.js
  src/components/Dashboard/Utilization/tests/__snapshots__/UtilizationItem.test.js.snap
Labels: size/XL

#432 Add tests for overview dashboard
  src/components/ClusterOverview/Alerts/fixtures/Alerts.fixture.js
  src/components/ClusterOverview/Alerts/tests/Alerts.test.js
  src/components/ClusterOverview/Alerts/tests/__snapshots__/Alerts.test.js.snap
  src/components/ClusterOverview/Capacity/fixtures/Capacity.fixture.js
  src/components/ClusterOverview/Capacity/tests/Capacity.test.js
  src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/ClusterOverview/Compliance/fixtures/Compliance.fixture.js
  src/components/ClusterOverview/Compliance/tests/Compliance.test.js
  src/components/ClusterOverview/Compliance/tests/__snapshots__/Compliance.test.js.snap
  src/components/ClusterOverview/Details/fixtures/Details.fixture.js
  src/components/ClusterOverview/Details/tests/Details.test.js
  src/components/ClusterOverview/Details/tests/__snapshots__/Details.test.js.snap
  src/components/ClusterOverview/Events/tests/Events.test.js
  src/components/ClusterOverview/Events/tests/__snapshots__/Events.test.js.snap
  src/components/ClusterOverview/Health/fixtures/Health.fixture.js
  src/components/ClusterOverview/Health/tests/Health.test.js
  src/components/ClusterOverview/Health/tests/__snapshots__/Health.test.js.snap
  src/components/ClusterOverview/Inventory/fixtures/Inventory.fixture.js
  src/components/ClusterOverview/Inventory/tests/Inventory.test.js
  src/components/ClusterOverview/Inventory/tests/__snapshots__/Inventory.test.js.snap
  src/components/ClusterOverview/TopConsumers/fixtures/TopConsumers.fixture.js
  src/components/ClusterOverview/TopConsumers/tests/TopConsumers.test.js
  src/components/ClusterOverview/TopConsumers/tests/__snapshots__/TopConsumers.test.js.snap
  src/components/ClusterOverview/Utilization/fixtures/Utilization.fixture.js
  src/components/ClusterOverview/Utilization/tests/Utilization.test.js
  src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/ClusterOverview/fixtures/ClusterOverview.fixture.js
  src/components/ClusterOverview/tests/ClusterOverview.test.js
  src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
Labels: size/XXL

#435 Time Axis - Utilization Card (Storage Overview)
  sass/components/Dashboard/utilization.scss
  src/components/StorageOverview/Utilization/Utilization.js
  src/components/StorageOverview/Utilization/tests/Utilization.test.js
  src/components/StorageOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/StorageOverview/tests/StorageOverview.test.js
  src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
  src/selectors/prometheus/selectors.js
Labels: size/XXL

#438 Add a controller address validation
  src/components/CreateBaremetalHostDialog/CreateBaremetalHostDialog.js
  src/components/CreateBaremetalHostDialog/tests/__snapshots__/CreateBaremetalHostDialog.test.js.snap
  src/constants/index.js
  src/utils/strings.js
  src/utils/tests/validation.test.js
  src/utils/validations.js
Labels: size/M

#441 Fix vddk mount path
  src/k8s/requests/v2v/constants.js
Labels: size/XS

#443 Delete new row when cancel is clicked (#430)
  src/components/Table/EditableDraggableTable.js
  src/components/Table/TableFactory.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js
  src/components/Wizard/CreateVmWizard/tests/NetworksTab.test.js
  src/components/Wizard/CreateVmWizard/tests/StorageTab.test.js
Labels: size/L

#442 Add tests for Storage Overview dashboards
  src/components/StorageOverview/Alerts/fixtures/Alerts.fixture.js
  src/components/StorageOverview/Alerts/tests/Alerts.test.js
  src/components/StorageOverview/Alerts/tests/__snapshots__/Alerts.test.js.snap
  src/components/StorageOverview/Capacity/fixtures/Capacity.fixture.js
  src/components/StorageOverview/Capacity/tests/Capacity.test.js
  src/components/StorageOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/StorageOverview/Details/fixtures/Details.fixture.js
  src/components/StorageOverview/Details/tests/Details.test.js
  src/components/StorageOverview/Details/tests/__snapshots__/Details.test.js.snap
  src/components/StorageOverview/Inventory/fixtures/Inventory.fixture.js
  src/components/StorageOverview/Inventory/tests/Inventory.test.js
  src/components/StorageOverview/Inventory/tests/__snapshots__/Inventory.test.js.snap
  src/components/StorageOverview/OCSHealth/Health.js
  src/components/StorageOverview/OCSHealth/fixtures/Health.fixture.js
  src/components/StorageOverview/OCSHealth/tests/Health.test.js
  src/components/StorageOverview/OCSHealth/tests/__snapshots__/Health.test.js.snap
  src/components/StorageOverview/StorageOverview.js
  src/components/StorageOverview/Utilization/fixtures/Utilization.fixture.js
  src/components/StorageOverview/Utilization/tests/Utilization.test.js
  src/components/StorageOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/StorageOverview/fixtures/StorageOverview.fixture.js
Labels: size/XXL

#447 Update string conversion to import (vmware)
  src/components/VmStatus/VmStatus.js
  src/components/VmStatus/tests/__snapshots__/VmStatus.test.js.snap
Labels: size/S

#448 [web-ui-v2.0.0] Update string conversion to import (vmware)
  src/components/VmStatus/VmStatus.js
  src/components/VmStatus/tests/__snapshots__/VmStatus.test.js.snap
Labels: size/S

#445 Display error on duplicate VM name in wizard
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/constants.js
  src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js
  src/components/Wizard/CreateVmWizard/validations/utils.js
  src/components/Wizard/CreateVmWizard/validations/validators.js
  src/components/Wizard/CreateVmWizard/validations/vmSettingsTabValidation.js
  src/tests/mocks/vm/vm_validation.mock.js
  src/utils/strings.js
  src/utils/tests/validation.test.js
  src/utils/validations.js
Labels: size/L

#392 Correct hostname display in VM overview tab
  src/components/Details/VmDetails/VmDetails.js
  src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap
  src/k8s/request.js
  src/selectors/vmi/selectors.js
Labels: size/M

#439 Refactor storage cards to use new props format.
  src/components/StorageOverview/Alerts/tests/Alerts.test.js
  src/components/StorageOverview/Events/Events.js
  src/components/StorageOverview/Events/fixtures/Events.fixture.js
  src/components/StorageOverview/Events/tests/Events.test.js
  src/components/StorageOverview/Events/tests/__snapshots__/Events.test.js.snap
  src/components/StorageOverview/Inventory/Inventory.js
  src/components/StorageOverview/Inventory/fixtures/Inventory.fixture.js
  src/components/StorageOverview/Inventory/tests/__snapshots__/Inventory.test.js.snap
  src/components/StorageOverview/OCSHealth/Health.js
  src/components/StorageOverview/OCSHealth/fixtures/Health.fixture.js
  src/components/StorageOverview/OCSHealth/tests/__snapshots__/Health.test.js.snap
  src/components/StorageOverview/StorageOverviewContext/StorageOverviewContext.js
  src/components/StorageOverview/StorageOverviewContext/index.js
  src/components/StorageOverview/TopConsumers/TopConsumers.js
  src/components/StorageOverview/TopConsumers/fixtures/TopConsumers.fixture.js
  src/components/StorageOverview/TopConsumers/tests/TopConsumers.test.js
  src/components/StorageOverview/TopConsumers/tests/__snapshots__/TopConsumers.test.js.snap
  src/components/StorageOverview/fixtures/StorageOverview.fixture.js
Labels: size/L

#450 Correct hostname display in VM overview tab
  src/components/Details/VmDetails/VmDetails.js
  src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap
  src/k8s/request.js
  src/selectors/vmi/selectors.js
Labels: size/M

#449 Display error on duplicate VM name in wizard
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/constants.js
  src/components/Wizard/CreateVmWizard/fixtures/CreateVmWizard.fixture.js
  src/components/Wizard/CreateVmWizard/tests/CreateVmWizard.test.js
  src/components/Wizard/CreateVmWizard/validations/utils.js
  src/components/Wizard/CreateVmWizard/validations/validators.js
  src/components/Wizard/CreateVmWizard/validations/vmSettingsTabValidation.js
  src/tests/mocks/vm/vm_validation.mock.js
  src/utils/strings.js
  src/utils/tests/validation.test.js
  src/utils/validations.js
Labels: size/L

#451 make details components safe for async requests
  src/components/Details/VmDetails/VmDetails.js
  src/components/Details/VmTemplateDetails/VmTemplateDetails.js
Labels: size/M

#446 Created dropdown component and integrated it with top consumer card
  sass/_components.scss
  sass/components/Dashboard/dashboard.scss
  sass/components/Dashboard/dropdown.scss
  src/components/Dashboard/DashboardCard/DashboardCardActionsBody.js
  src/components/Dashboard/DashboardCard/fixtures/DashboardCardActionsBody.fixture.js
  src/components/Dashboard/DashboardCard/tests/DashboardCardActionsBody.test.js
  src/components/Dashboard/DashboardCard/tests/__snapshots__/DashboardCardActionsBody.test.js.snap
  src/components/Form/Dropdown.js
  src/components/Form/FormFactory.js
  src/components/Form/tests/__snapshots__/FormFactory.test.js.snap
  src/components/StorageOverview/TopConsumers/TopConsumers.js
  src/components/StorageOverview/TopConsumers/fixtures/TopConsumers.fixture.js
  src/components/StorageOverview/TopConsumers/strings.js
  src/components/StorageOverview/TopConsumers/tests/TopConsumers.test.js
  src/components/StorageOverview/TopConsumers/tests/__snapshots__/TopConsumers.test.js.snap
  src/components/StorageOverview/fixtures/StorageOverview.fixture.js
  src/selectors/prometheus/storage.js
Labels: size/XL

#453 Fix V2V inital state
  src/components/VmStatus/VmStatus.js
  src/components/VmStatus/tests/__snapshots__/VmStatus.test.js.snap
  src/k8s/objects/v2v/vmware/conversionPod.js
  src/k8s/objects/v2v/vmware/vmWareDeployment.js
  src/utils/status/pod/constants.js
  src/utils/status/vm/constants.js
  src/utils/status/vm/vmStatus.js
Labels: size/M

#452 Fix rendered disk size <1Gi
  src/components/Table/EditableDraggableTable.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/fixtures/CreateVmWizard.fixture.js
  src/components/Wizard/CreateVmWizard/fixtures/StorageTab.fixture.js
  src/components/Wizard/CreateVmWizard/strings.js
  src/components/Wizard/CreateVmWizard/tests/NetworksTab.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/NetworksTab.test.js.snap
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/StorageTab.test.js.snap
  src/k8s/objects/pvc/pvc.js
  src/k8s/request.js
  src/k8s/requests/v2v/importVmware.js
  src/k8s/requests/v2v/startV2VvmwareController.js
  src/utils/utils.js
Labels: size/L

#455 Fix VMware naming
  src/components/VmStatus/VmStatus.js
  src/components/VmStatus/tests/__snapshots__/VmStatus.test.js.snap
Labels: size/XS

#457 Backport: Fix rendered disk size <1Gi
  src/components/Table/EditableDraggableTable.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/StorageTab.js
  src/components/Wizard/CreateVmWizard/fixtures/CreateVmWizard.fixture.js
  src/components/Wizard/CreateVmWizard/fixtures/StorageTab.fixture.js
  src/components/Wizard/CreateVmWizard/strings.js
  src/components/Wizard/CreateVmWizard/tests/NetworksTab.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/NetworksTab.test.js.snap
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/StorageTab.test.js.snap
  src/k8s/objects/pvc/pvc.js
  src/k8s/request.js
  src/k8s/requests/v2v/importVmware.js
  src/k8s/requests/v2v/startV2VvmwareController.js
  src/utils/utils.js
Labels: size/L

#456 Backport: Fix V2V inital state
  src/components/VmStatus/VmStatus.js
  src/components/VmStatus/tests/__snapshots__/VmStatus.test.js.snap
  src/k8s/objects/v2v/vmware/conversionPod.js
  src/k8s/objects/v2v/vmware/vmWareDeployment.js
  src/utils/status/pod/constants.js
  src/utils/status/vm/constants.js
  src/utils/status/vm/vmStatus.js
Labels: size/M

#461 Customize imagePullPolicy for v2v images
  src/config/index.js
  src/k8s/objects/v2v/vmware/conversionPod.js
  src/k8s/objects/v2v/vmware/vmWareDeployment.js
Labels: size/XS

#460 update-capacity-card-css
  sass/components/Dashboard/capacity.scss
Labels: size/XS

#464 Add host-related selectors
  src/selectors/host/selectors.js
Labels: size/XS

#467 Fix import of validateVmName()
  src/components/Dialog/CloneDialog/CloneDialog.js
  src/utils/validations.js
Labels: size/M

#463 Fix name line break
  sass/components/VmDetails/vm-details.scss
Labels: size/XS

#466 Improve empty network name message
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/strings.js
Labels: size/XS

#468 Fix import of validateVmName()
  src/components/Dialog/CloneDialog/CloneDialog.js
  src/utils/validations.js
Labels: size/M

#472 Improve empty network name message
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/strings.js
Labels: size/XS

#459 Added dropdown for alerts card in storage dashboard
  src/components/Dashboard/strings.js
  src/components/StorageOverview/Alerts/Alerts.js
  src/components/StorageOverview/Alerts/tests/Alerts.test.js
  src/components/StorageOverview/Alerts/tests/__snapshots__/Alerts.test.js.snap
Labels: size/L

#473 Fix baremetal status popover
  config/cosmos.webpack.config.js
  config/jest.config.js
  config/jest.style.mock.js
  package.json
  sass/components/Status/status.scss
  src/components/BareMetalHosts/StatusComponents.js
  src/components/BareMetalHosts/tests/__snapshots__/StatusComponents.test.js.snap
  src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/Dashboard/Capacity/tests/__snapshots__/CapacityItem.test.js.snap
  src/components/Dashboard/Utilization/tests/__snapshots__/UtilizationBody.test.js.snap
  src/components/Dashboard/Utilization/tests/__snapshots__/UtilizationItem.test.js.snap
  src/components/NodeStatus/NodeStatus.js
  src/components/Status/Status.js
  src/components/Status/fixtures/Status.fixture.js
  src/components/StorageOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/StorageOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  yarn.lock
Labels: size/XL

#471 Do not close Create VM Wizard when clicked outside of modal
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap
Labels: size/XS

#477 Do not close Create VM Wizard when clicked outside of modal
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap
Labels: size/XS

#476 Do not allow floats as memory value
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap
  src/components/Wizard/CreateVmWizard/validations/vmSettingsTabValidation.js
  src/utils/validations.js
Labels: size/S

#478 fix os picking
  src/components/Wizard/CreateVmWizard/stateUpdate/providers/prefillVmStateUpdate.js
Labels: size/S

#480 Do not allow floats as memory value
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/CreateVmWizard.test.js.snap
  src/components/Wizard/CreateVmWizard/validations/vmSettingsTabValidation.js
  src/utils/validations.js
Labels: size/S

#462 Integrated dropdown to utilization card
  src/components/StorageOverview/Utilization/Utilization.js
  src/components/StorageOverview/Utilization/fixtures/Utilization.fixture.js
  src/components/StorageOverview/Utilization/strings.js
  src/components/StorageOverview/Utilization/tests/Utilization.test.js
  src/components/StorageOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
Labels: size/XL

#465 Added purecomponent for storage dashboard
  src/components/StorageOverview/Capacity/Capacity.js
  src/components/StorageOverview/DataResiliency/DataResiliency.js
  src/components/StorageOverview/Details/Details.js
  src/components/StorageOverview/Events/Events.js
  src/components/StorageOverview/Events/fixtures/Events.fixture.js
  src/components/StorageOverview/Events/tests/__snapshots__/Events.test.js.snap
  src/components/StorageOverview/OCSHealth/Health.js
  src/components/StorageOverview/StorageOverview.js
  src/components/StorageOverview/Utilization/Utilization.js
  src/components/StorageOverview/fixtures/StorageOverview.fixture.js
Labels: size/L

#484 fix: reset OS when re-selecting VM for import
  src/components/Wizard/CreateVmWizard/stateUpdate/providers/prefillVmStateUpdate.js
Labels: size/S

#427 Converting vm-status from using link to pf4 popover
  sass/components/Status/status.scss
  src/components/BareMetalHosts/tests/__snapshots__/StatusComponents.test.js.snap
  src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap
  src/components/Status/Status.js
  src/components/Status/fixtures/Status.fixture.js
  src/components/Status/tests/Status.test.js
  src/components/Status/tests/__snapshots__/Status.test.js.snap
  src/components/VmStatus/VmStatus.js
  src/components/VmStatus/fixtures/VmStatus.fixture.js
  src/components/VmStatus/strings.js
  src/components/VmStatus/tests/__snapshots__/VmStatus.test.js.snap
  src/utils/status/vm/constants.js
Labels: size/XXL

#485 CreateVmWizard WMware - fix: fields become inactive after the VM is picked
  src/components/Wizard/CreateVmWizard/stateUpdate/providers/vmWareStateUpdate.js
Labels: size/S
