Repository kubevirt/web-ui-components, pull requests merged in 2019-04, with the labels that each got.

#292 Add a component for creating baremetal hosts
  sass/_components.scss
  sass/components/CreateBaremetalHostDialog/create-baremetal-host-dialog.scss
  src/components/CreateBaremetalHostDialog/CreateBaremetalHostDialog.js
  src/components/CreateBaremetalHostDialog/fixtures/CreateBaremetalHostDialog.fixture.js
  src/components/CreateBaremetalHostDialog/index.js
  src/components/CreateBaremetalHostDialog/strings.js
  src/components/CreateBaremetalHostDialog/tests/CreateBaremetalHostDialog.test.js
  src/components/CreateBaremetalHostDialog/tests/__snapshots__/CreateBaremetalHostDialog.test.js.snap
  src/components/Loading/Loading.js
  src/index.js
  src/k8s/request.js
  src/k8s/requests/hosts/index.js
Labels: size/L

#287 Render VmDetails with deleted template curreclty.
  sass/_components.scss
  sass/components/Flavor/flavor.scss
  src/components/Details/Description/tests/__snapshots__/Description.test.js.snap
  src/components/Details/Flavor/Flavor.js
  src/components/Details/Flavor/fixtures/Flavor.fixture.js
  src/components/Details/Flavor/tests/Flavor.test.js
  src/components/Details/Flavor/tests/__snapshots__/Flavor.test.js.snap
  src/components/Details/VmDetails/VmDetails.js
  src/components/Details/VmDetails/fixtures/VmDetails.fixture.js
  src/components/Details/VmDetails/tests/VmDetails.test.js
  src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap
  src/components/Details/VmTemplateDetails/VmTemplateDetails.js
  src/components/Details/VmTemplateDetails/fixtures/VmTemplateDetails.fixture.js
  src/components/Details/VmTemplateDetails/tests/VmTemplateDetails.test.js
  src/components/Details/VmTemplateDetails/tests/__snapshots__/VmTemplateDetails.test.js.snap
  src/components/InlineEdit/InlineEdit.js
  src/selectors/vm/selectors.js
  src/tests/mocks/user_template/container-cloud.mock.js
  src/tests/mocks/user_template/index.js
Labels: size/XXL

#299 Refactor Inventory and Details cards and move their parts to Dashboard folder
  sass/_components.scss
  sass/components/Dashboard/detail.scss
  sass/components/Dashboard/inventory.scss
  src/components/ClusterOverview/ClusterOverview.js
  src/components/ClusterOverview/Details/ClusterDetails.js
  src/components/ClusterOverview/Details/Details.js
  src/components/ClusterOverview/Details/fixtures/ClusterDetails.fixture.js
  src/components/ClusterOverview/Details/fixtures/Details.fixture.js
  src/components/ClusterOverview/Details/tests/ClusterDetails.test.js
  src/components/ClusterOverview/Details/tests/__snapshots__/ClusterDetails.test.js.snap
  src/components/ClusterOverview/Details/tests/__snapshots__/Details.test.js.snap
  src/components/ClusterOverview/Inventory/Inventory.js
  src/components/ClusterOverview/Inventory/tests/__snapshots__/Inventory.test.js.snap
  src/components/ClusterOverview/fixtures/ClusterOverview.fixture.js
  src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
  src/components/Dashboard/Details/DetailItem.js
  src/components/Dashboard/Details/DetailsBody.js
  src/components/Dashboard/Details/fixtures/DetailItem.fixture.js
  src/components/Dashboard/Details/fixtures/DetailsBody.fixture.js
  src/components/Dashboard/Details/tests/DetailItem.test.js
  src/components/Dashboard/Details/tests/DetailsBody.test.js
  src/components/Dashboard/Details/tests/__snapshots__/DetailItem.test.js.snap
  src/components/Dashboard/Details/tests/__snapshots__/DetailsBody.test.js.snap
  src/components/Dashboard/Inventory/InventoryItemStatus.js
  src/components/Dashboard/Inventory/InventoryRow.js
  src/components/Dashboard/Inventory/fixtures/InventoryItemStatus.fixture.js
  src/components/Dashboard/Inventory/fixtures/InventoryRow.fixture.js
  src/components/Dashboard/Inventory/tests/InventoryItemStatus.test.js
  src/components/Dashboard/Inventory/tests/InventoryRow.test.js
  src/components/Dashboard/Inventory/tests/__snapshots__/InventoryItemStatus.test.js.snap
  src/components/Dashboard/Inventory/tests/__snapshots__/InventoryRow.test.js.snap
Labels: size/XL

#296 Fix vmStatus ordering
  src/utils/status/vm/vmStatus.js
Labels: size/XS

#298 Add binding type to NICs
  src/components/CreateDeviceRow/CreateDeviceRow.js
  src/components/CreateNicRow/CreateNicRow.js
  src/components/CreateNicRow/tests/__snapshots__/CreateNicRow.test.js.snap
  src/components/Form/FormFactory.js
  src/components/Table/EditableDraggableTable.js
  src/components/Table/TableFactory.js
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/NetworksTab.js
  src/components/Wizard/CreateVmWizard/constants.js
  src/components/Wizard/CreateVmWizard/strings.js
  src/components/Wizard/CreateVmWizard/tests/NetworksTab.test.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/NetworksTab.test.js.snap
  src/k8s/vmBuilder.js
  src/selectors/vm/selectors.js
  src/utils/patches.js
  src/utils/utils.js
Labels: size/L

#302 Add services to VM Details
  src/components/Details/Services/Services.js
  src/components/Details/Services/fixtures/Services.fixture.js
  src/components/Details/Services/tests/Services.test.js
  src/components/Details/Services/tests/__snapshots__/Services.test.js.snap
  src/components/Details/VmDetails/VmDetails.js
  src/components/Details/VmDetails/fixtures/VmDetails.fixture.js
  src/components/Details/VmDetails/tests/VmDetails.test.js
  src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap
  src/selectors/service/combined.js
  src/selectors/service/index.js
Labels: size/XL

#303 Fix resizing of the utilization c3charts
  src/components/ClusterOverview/Utilization/Utilization.js
Labels: size/XS

#301 Refactor Capacity Card and extract CapacityBody and CapacityItem to D…
  sass/_components.scss
  sass/components/Dashboard/capacity.scss
  src/components/ClusterOverview/Capacity/Capacity.js
  src/components/ClusterOverview/Capacity/fixtures/Capacity.fixture.js
  src/components/ClusterOverview/Capacity/tests/Capacity.test.js
  src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/ClusterOverview/ClusterOverview.js
  src/components/ClusterOverview/fixtures/ClusterOverview.fixture.js
  src/components/Dashboard/Capacity/CapacityBody.js
  src/components/Dashboard/Capacity/CapacityItem.js
  src/components/Dashboard/Capacity/fixtures/CapacityBody.fixture.js
  src/components/Dashboard/Capacity/fixtures/CapacityItem.fixture.js
  src/components/Dashboard/Capacity/strings.js
  src/components/Dashboard/Capacity/tests/CapacityBody.test.js
  src/components/Dashboard/Capacity/tests/CapacityItem.test.js
  src/components/Dashboard/Capacity/tests/__snapshots__/CapacityBody.test.js.snap
  src/components/Dashboard/Capacity/tests/__snapshots__/CapacityItem.test.js.snap
  src/selectors/prometheus/index.js
  src/selectors/prometheus/selectors.js
  src/utils/utils.js
Labels: size/XL

#306 Wrap capacity items
  sass/components/Dashboard/capacity.scss
Labels: size/XS

#305 Match VM Services against all labels
  src/components/Details/Services/fixtures/Services.fixture.js
  src/components/Details/VmDetails/fixtures/VmDetails.fixture.js
  src/components/Details/VmDetails/tests/VmDetails.test.js
  src/selectors/service/combined.js
  src/selectors/service/index.js
  src/selectors/service/selectors.js
  src/selectors/vm/selectors.js
Labels: size/M

#307 ClusterOverview: refactor Utilization card and connect
  sass/_components.scss
  sass/components/ClusterOverview/utilization.scss
  sass/components/Dashboard/utilization.scss
  src/components/ClusterOverview/ClusterOverview.js
  src/components/ClusterOverview/Utilization/Utilization.js
  src/components/ClusterOverview/Utilization/fixtures/Utilization.fixture.js
  src/components/ClusterOverview/Utilization/tests/Utilization.test.js
  src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/ClusterOverview/fixtures/ClusterOverview.fixture.js
  src/components/ClusterOverview/index.js
  src/components/Dashboard/Capacity/CapacityItem.js
  src/components/Dashboard/Utilization/UtilizationBody.js
  src/components/Dashboard/Utilization/UtilizationItem.js
  src/components/Dashboard/Utilization/fixtures/UtilizationBody.fixture.js
  src/components/Dashboard/Utilization/fixtures/UtilizationItem.fixture.js
  src/components/Dashboard/Utilization/strings.js
  src/components/Dashboard/Utilization/tests/UtilizationBody.test.js
  src/components/Dashboard/Utilization/tests/UtilizationItem.test.js
  src/components/Dashboard/Utilization/tests/__snapshots__/UtilizationBody.test.js.snap
  src/components/Dashboard/Utilization/tests/__snapshots__/UtilizationItem.test.js.snap
  src/selectors/prometheus/selectors.js
Labels: size/XL

#312 Add hosts to the inventory card
  src/components/ClusterOverview/Inventory/Inventory.js
  src/components/ClusterOverview/Inventory/tests/__snapshots__/Inventory.test.js.snap
  src/components/ClusterOverview/Inventory/utils.js
  src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
  src/utils/status/host/constants.js
  src/utils/status/host/hostStatus.js
  src/utils/status/host/index.js
Labels: size/M

#309 ClusterOverview: Add Memory to Utilization
  src/components/ClusterOverview/Utilization/Utilization.js
  src/components/ClusterOverview/Utilization/fixtures/Utilization.fixture.js
  src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/selectors/prometheus/selectors.js
Labels: size/L

#308 ClusterOverview: Improve prometheus query for CPU Capacity
  src/components/ClusterOverview/Capacity/Capacity.js
  src/components/ClusterOverview/Capacity/fixtures/Capacity.fixture.js
  src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/utils/utils.js
Labels: size/M

#315 ClusterOverview: Merge CPU/mem Capacity and Utilization stats
  src/components/ClusterOverview/Capacity/Capacity.js
  src/components/ClusterOverview/Capacity/fixtures/Capacity.fixture.js
  src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/selectors/prometheus/selectors.js
Labels: size/M

#314 Dashboard, Utilization: Render in narrow container
  package.json
  sass/components/Dashboard/utilization.scss
  src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/Dashboard/Utilization/UtilizationItem.js
  src/components/Dashboard/Utilization/tests/UtilizationBody.test.js
  src/components/Dashboard/Utilization/tests/UtilizationItem.test.js
  src/components/Dashboard/Utilization/tests/__snapshots__/UtilizationBody.test.js.snap
  src/components/Dashboard/Utilization/tests/__snapshots__/UtilizationItem.test.js.snap
  yarn.lock
Labels: size/XXL

#289 Refactor TopConsumers and add Workload and Infrastructure metrics
  sass/_components.scss
  sass/components/ClusterOverview/consumers.scss
  sass/components/Dashboard/consumers.scss
  src/components/ClusterOverview/ClusterOverview.js
  src/components/ClusterOverview/TopConsumers/TopConsumers.js
  src/components/ClusterOverview/TopConsumers/fixtures/TopConsumers.fixture.js
  src/components/ClusterOverview/TopConsumers/strings.js
  src/components/ClusterOverview/TopConsumers/tests/TopConsumers.test.js
  src/components/ClusterOverview/TopConsumers/tests/__snapshots__/TopConsumers.test.js.snap
  src/components/ClusterOverview/TopConsumers/utils.js
  src/components/ClusterOverview/fixtures/ClusterOverview.fixture.js
  src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
  src/components/Dashboard/TopConsumers/ConsumerItem.js
  src/components/Dashboard/TopConsumers/ConsumersFilter.js
  src/components/Dashboard/TopConsumers/ConsumersResults.js
  src/components/Dashboard/TopConsumers/fixtures/ConsumerItem.fixture.js
  src/components/Dashboard/TopConsumers/fixtures/ConsumersFilter.fixture.js
  src/components/Dashboard/TopConsumers/fixtures/ConsumersResults.fixture.js
  src/components/Dashboard/TopConsumers/tests/ConsumerItem.test.js
  src/components/Dashboard/TopConsumers/tests/ConsumersFilter.test.js
  src/components/Dashboard/TopConsumers/tests/ConsumersResults.test.js
  src/components/Dashboard/TopConsumers/tests/__snapshots__/ConsumerItem.test.js.snap
  src/components/Dashboard/TopConsumers/tests/__snapshots__/ConsumersFilter.test.js.snap
  src/components/Dashboard/TopConsumers/tests/__snapshots__/ConsumersResults.test.js.snap
  src/components/Dashboard/TopConsumers/utils.js
  src/selectors/prometheus/selectors.js
Labels: size/XXL

#316 Do not filter by namespace if vm is missing a namespace
  src/components/CreateNicRow/CreateNicRow.js
  src/components/CreateNicRow/tests/CreateNicRow.test.js
Labels: size/XS

#319 Remove DashboardHeader
  src/components/ClusterOverview/ClusterOverview.js
  src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
  src/components/Dashboard/DashboardHeader.js
  src/components/Dashboard/fixtures/DashboardHeader.fixture.js
  src/components/Dashboard/index.js
  src/components/Dashboard/tests/Dashboard.api.test.js
  src/components/Dashboard/tests/DashboardHeader.test.js
  src/components/Dashboard/tests/__snapshots__/Dashboard.api.test.js.snap
  src/components/Dashboard/tests/__snapshots__/DashboardHeader.test.js.snap
  src/components/StorageOverview/StorageOverview.js
  src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
Labels: size/M

#318 Adding Capacity Card to Storage Overview
  src/components/StorageOverview/Capacity/Capacity.js
  src/components/StorageOverview/Capacity/fixtures/Capacity.fixture.js
  src/components/StorageOverview/Capacity/tests/Capacity.test.js
  src/components/StorageOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/StorageOverview/StorageOverview.js
  src/components/StorageOverview/fixtures/StorageOverview.fixture.js
Labels: size/L

#328 Change Font size and Units in Capacity card
  src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/Dashboard/Capacity/CapacityItem.js
  src/components/Dashboard/Capacity/tests/__snapshots__/CapacityItem.test.js.snap
  src/components/StorageOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/utils/tests/utils.test.js
  src/utils/utils.js
Labels: size/M

#329 Add Alerts Card
  sass/_components.scss
  sass/components/ClusterOverview/cluster-overview.scss
  sass/components/Dashboard/alert.scss
  src/components/ClusterOverview/Alerts/Alerts.js
  src/components/ClusterOverview/Alerts/fixtures/Alerts.fixture.js
  src/components/ClusterOverview/Alerts/tests/Alerts.test.js
  src/components/ClusterOverview/Alerts/tests/__snapshots__/Alerts.test.js.snap
  src/components/ClusterOverview/Alerts/utils.js
  src/components/ClusterOverview/ClusterOverview.js
  src/components/ClusterOverview/fixtures/ClusterOverview.fixture.js
  src/components/Dashboard/Alert/AlertItem.js
  src/components/Dashboard/Alert/AlertsBody.js
  src/components/Dashboard/Alert/fixtures/AlertItem.fixture.js
  src/components/Dashboard/Alert/fixtures/AlertsBody.fixture.js
  src/components/Dashboard/Alert/tests/AlertItem.test.js
  src/components/Dashboard/Alert/tests/AlertsBody.test.js
  src/components/Dashboard/Alert/tests/__snapshots__/AlertItem.test.js.snap
  src/components/Dashboard/Alert/tests/__snapshots__/AlertsBody.test.js.snap
  src/selectors/prometheus/alerts.js
  src/selectors/prometheus/index.js
Labels: size/L

#330 Added Performace/Utilization card
  src/components/StorageOverview/StorageOverview.js
  src/components/StorageOverview/Utilization/Utilization.js
  src/components/StorageOverview/Utilization/fixtures/Utilization.fixture.js
  src/components/StorageOverview/Utilization/tests/Utilization.test.js
  src/components/StorageOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/StorageOverview/fixtures/StorageOverview.fixture.js
  src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
Labels: size/L

#322 Utilization: Add Disk Usage chart
  src/components/ClusterOverview/Capacity/Capacity.js
  src/components/ClusterOverview/Capacity/fixtures/Capacity.fixture.js
  src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/ClusterOverview/Utilization/Utilization.js
  src/components/ClusterOverview/Utilization/fixtures/Utilization.fixture.js
  src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
Labels: size/L

#336 Fix css for events dashboard card
  sass/components/Dashboard/events.scss
  src/components/ClusterOverview/Events/Events.js
  src/components/ClusterOverview/Events/tests/__snapshots__/Events.test.js.snap
  src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
  src/components/StorageOverview/Events/Events.js
  src/components/StorageOverview/Events/tests/__snapshots__/Events.test.js.snap
  src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
Labels: size/M

#338 Align byte units to tectonic ones.
  src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/utils/tests/utils.test.js
  src/utils/utils.js
Labels: size/M

#344 Typo changes to storage dashboard
  src/components/StorageOverview/Details/Details.js
  src/components/StorageOverview/Details/tests/__snapshots__/Details.test.js.snap
  src/components/StorageOverview/OCSHealth/HealthBody.js
  src/components/StorageOverview/Utilization/Utilization.js
  src/components/StorageOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
Labels: size/M

#340 Do not map vm status off to status ok
  sass/components/Dashboard/inventory.scss
  src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/ClusterOverview/Inventory/tests/__snapshots__/Inventory.test.js.snap
  src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
  src/components/Dashboard/Inventory/InventoryItemStatus.js
  src/components/Dashboard/Inventory/fixtures/InventoryItemStatus.fixture.js
  src/components/Dashboard/Inventory/tests/__snapshots__/InventoryItemStatus.test.js.snap
  src/components/Dashboard/Inventory/tests/__snapshots__/InventoryRow.test.js.snap
  src/components/Dashboard/Inventory/utils.js
  src/components/StorageOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
  src/components/VmConsoles/tests/__snapshots__/DesktopViewerSelector.test.js.snap
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/ResultTabRow.test.js.snap
  src/tests/mocks/vm/cloudInitTestVm.mock.js
  src/tests/mocks/vm/vm.mock.js
  src/utils/status/vm/constants.js
  src/utils/status/vm/fixtures/vmStatus.fixture.js
  src/utils/status/vm/vmStatus.js
Labels: size/L

#345 Pass LoadingComponent to inventory rows
  src/components/ClusterOverview/Inventory/Inventory.js
  src/components/Dashboard/Inventory/InventoryRow.js
  src/components/StorageOverview/Inventory/Inventory.js
Labels: size/M

#347 remove rhhi version
  src/components/ClusterOverview/Details/Details.js
  src/components/ClusterOverview/Details/tests/__snapshots__/Details.test.js.snap
  src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
Labels: size/M

#293 Add Host Status selector and components
  sass/_components.scss
  sass/components/HostStatus/host-status.scss
  src/components/BareMetalHosts/BaremetalHostStatus.js
  src/components/BareMetalHosts/StatusComponents.js
  src/components/BareMetalHosts/fixtures/BaremetalHostStatus.fixture.js
  src/components/BareMetalHosts/fixtures/StatusComponents.fixture.js
  src/components/BareMetalHosts/index.js
  src/components/BareMetalHosts/tests/BaremetalHostStatus.test.js
  src/components/BareMetalHosts/tests/StatusComponents.test.js
  src/components/BareMetalHosts/tests/__snapshots__/BaremetalHostStatus.test.js.snap
  src/components/BareMetalHosts/tests/__snapshots__/StatusComponents.test.js.snap
  src/index.js
  src/selectors/host/selectors.js
  src/utils/status/host/constants.js
  src/utils/status/host/hostStatus.js
  src/utils/status/index.js
Labels: size/L

#339 Add BaremetalHostRole component
  src/components/BareMetalHosts/BaremetalHostRole.js
  src/components/BareMetalHosts/fixtures/BaremetalHostRole.fixture.js
  src/components/BareMetalHosts/index.js
  src/components/BareMetalHosts/tests/BaremetalHostRole.test.js
  src/components/BareMetalHosts/tests/__snapshots__/BaremetalHostRole.test.js.snap
  src/selectors/host/selectors.js
Labels: size/M

#333 Add selector to check if host can add machine
  src/selectors/host/selectors.js
  src/utils/status/host/hostStatus.js
Labels: size/XS

#350 Add default host status when host does not have status data
  src/selectors/host/selectors.js
  src/utils/status/host/hostStatus.js
Labels: size/XS

#331 Rename cnv.io labels to kubevirt.io
  src/components/Details/VmDetails/fixtures/VmDetails.fixture.js
  src/components/Details/common/tests/details.js
  src/components/VmConsoles/tests/__snapshots__/DesktopViewerSelector.test.js.snap
  src/components/Wizard/CreateVmWizard/providers/tests/__snapshots__/VCenterInstances.test.js.snap
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/ResultTabRow.test.js.snap
  src/constants/index.js
  src/k8s/objects/template/fedora28.js
  src/k8s/objects/template/rhel-high-p.js
  src/k8s/objects/template/rhel75.js
  src/k8s/objects/template/ubuntu1804.js
  src/k8s/objects/template/windows.js
  src/k8s/tests/request.test.js
  src/tests/mocks/user_template/container-cloud.mock.js
  src/tests/mocks/user_template/container-multus.mock.js
  src/tests/mocks/user_template/container.mock.js
  src/tests/mocks/user_template/pvc.mock.js
  src/tests/mocks/user_template/pxe-dv.mock.js
  src/tests/mocks/user_template/pxe-pvc.mock.js
  src/tests/mocks/user_template/pxe.mock.js
  src/tests/mocks/user_template/url-flavor.mock.js
  src/tests/mocks/user_template/url-nonetwork.mock.js
  src/tests/mocks/user_template/url.mock.js
  src/tests/mocks/vm/cloudInitTestVm.mock.js
  src/tests/mocks/vm/vm.mock.js
  src/utils/tests/templates.test.js
Labels: size/L

#335 [Cluster dashboard] Indicate when hosts are in progress
  src/components/Dashboard/Inventory/utils.js
Labels: size/XS

#326 Added data resiliency card
  sass/_components.scss
  sass/components/StorageOverview/data-resiliency.scss
  src/components/StorageOverview/DataResiliency/DataResiliency.js
  src/components/StorageOverview/DataResiliency/fixtures/DataResiliency.fixture.js
  src/components/StorageOverview/DataResiliency/tests/DataResiliency.test.js
  src/components/StorageOverview/DataResiliency/tests/__snapshots__/DataResiliency.test.js.snap
  src/components/StorageOverview/StorageOverview.js
  src/components/StorageOverview/fixtures/StorageOverview.fixture.js
Labels: size/L

#348 Alerts component for storage overview tab
  sass/components/ClusterOverview/cluster-overview.scss
  sass/components/Dashboard/dashboard.scss
  src/components/ClusterOverview/ClusterOverview.js
  src/components/StorageOverview/Alerts/Alerts.js
  src/components/StorageOverview/Alerts/fixtures/Alerts.fixture.js
  src/components/StorageOverview/Alerts/tests/Alerts.test.js
  src/components/StorageOverview/Alerts/tests/__snapshots__/Alerts.test.js.snap
  src/components/StorageOverview/Alerts/utils.js
  src/components/StorageOverview/StorageOverview.js
  src/components/StorageOverview/fixtures/StorageOverview.fixture.js
  src/selectors/prometheus/alerts.js
Labels: size/L

#349 Added top consumer card for storage dashboard
  sass/_components.scss
  sass/components/StorageOverview/top-consumer.scss
  src/components/StorageOverview/StorageOverview.js
  src/components/StorageOverview/TopConsumers/TopConsumers.js
  src/components/StorageOverview/TopConsumers/fixtures/TopConsumers.fixture.js
  src/components/StorageOverview/TopConsumers/tests/TopConsumers.test.js
  src/components/StorageOverview/TopConsumers/tests/__snapshots__/TopConsumers.test.js.snap
  src/components/StorageOverview/fixtures/StorageOverview.fixture.js
  src/selectors/prometheus/storage.js
  src/utils/utils.js
Labels: size/L

#342 Adding Health in Dashboard
  sass/_components.scss
  sass/components/Dashboard/health.scss
  sass/components/StorageOverview/ocs-health.scss
  src/components/Dashboard/Health/HealthBody.js
  src/components/Dashboard/Health/HealthItem.js
  src/components/Dashboard/Health/fixtures/HealthBody.fixture.js
  src/components/Dashboard/Health/fixtures/HealthItem.fixture.js
  src/components/Dashboard/Health/tests/HealthBody.test.js
  src/components/Dashboard/Health/tests/HealthItem.test.js
  src/components/Dashboard/Health/tests/__snapshots__/HealthBody.test.js.snap
  src/components/Dashboard/Health/tests/__snapshots__/HealthItem.test.js.snap
  src/components/StorageOverview/OCSHealth/Health.js
  src/components/StorageOverview/OCSHealth/HealthBody.js
  src/components/StorageOverview/OCSHealth/fixtures/HealthBody.fixture.js
  src/components/StorageOverview/OCSHealth/strings.js
  src/components/StorageOverview/OCSHealth/tests/HealthBody.test.js
  src/components/StorageOverview/OCSHealth/tests/__snapshots__/Health.test.js.snap
  src/components/StorageOverview/OCSHealth/tests/__snapshots__/HealthBody.test.js.snap
Labels: size/L

#357 Fix Dashboard Health
  sass/components/Dashboard/health.scss
  src/components/Dashboard/Health/fixtures/HealthItem.fixture.js
  src/components/Dashboard/Health/tests/__snapshots__/HealthBody.test.js.snap
  src/components/Dashboard/Health/tests/__snapshots__/HealthItem.test.js.snap
  src/components/StorageOverview/OCSHealth/Health.js
  src/components/StorageOverview/OCSHealth/tests/__snapshots__/Health.test.js.snap
Labels: size/M

#355 Add additional host, machine and node selectors
  src/selectors/host/selectors.js
  src/selectors/index.js
  src/selectors/machine/combined.js
  src/selectors/machine/index.js
  src/selectors/node/index.js
  src/selectors/node/selectors.js
  src/utils/status/host/fixtures/hostStatus.fixture.js
  src/utils/status/host/hostStatus.js
  src/utils/status/host/tests/hostStatus.test.js
Labels: size/L

#325 [Cluster overview] Add disks to inventory
  src/components/ClusterOverview/Inventory/Inventory.js
  src/components/ClusterOverview/Inventory/tests/__snapshots__/Inventory.test.js.snap
  src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
  src/components/Dashboard/Inventory/utils.js
  src/constants/index.js
  src/constants/storage.js
Labels: size/M

#358 Changed the order of charts, added recovery chart in performance card
  sass/components/Dashboard/utilization.scss
  src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/Dashboard/Utilization/UtilizationItem.js
  src/components/Dashboard/Utilization/tests/__snapshots__/UtilizationBody.test.js.snap
  src/components/Dashboard/Utilization/tests/__snapshots__/UtilizationItem.test.js.snap
  src/components/StorageOverview/Utilization/Utilization.js
  src/components/StorageOverview/Utilization/fixtures/Utilization.fixture.js
  src/components/StorageOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
Labels: size/L

#352 updates:dashboard
  sass/components/ClusterOverview/cluster-overview.scss
  sass/components/ClusterOverview/health.scss
  sass/components/Dashboard/dashboard.scss
  sass/components/Dashboard/detail.scss
  sass/components/Dashboard/health.scss
  sass/components/Dashboard/inventory.scss
  src/components/ClusterOverview/Alerts/tests/__snapshots__/Alerts.test.js.snap
  src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/ClusterOverview/ClusterOverview.js
  src/components/ClusterOverview/Compliance/tests/__snapshots__/Compliance.test.js.snap
  src/components/ClusterOverview/Details/Details.js
  src/components/ClusterOverview/Details/tests/__snapshots__/Details.test.js.snap
  src/components/ClusterOverview/Events/tests/__snapshots__/Events.test.js.snap
  src/components/ClusterOverview/Health/HealthBody.js
  src/components/ClusterOverview/Health/tests/__snapshots__/Health.test.js.snap
  src/components/ClusterOverview/Health/tests/__snapshots__/HealthBody.test.js.snap
  src/components/ClusterOverview/Inventory/tests/__snapshots__/Inventory.test.js.snap
  src/components/ClusterOverview/TopConsumers/tests/__snapshots__/TopConsumers.test.js.snap
  src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
  src/components/Dashboard/DashboardCard/DashboardCardTitle.js
  src/components/Dashboard/DashboardCard/DashboardCardTitleHelp.js
  src/components/Dashboard/DashboardCard/tests/__snapshots__/DashboardCardTitle.test.js.snap
  src/components/Dashboard/DashboardCard/tests/__snapshots__/DashboardCardTitleHelp.test.js.snap
  src/components/Dashboard/Health/HealthBody.js
  src/components/Dashboard/Health/HealthItem.js
  src/components/Dashboard/Health/tests/__snapshots__/HealthBody.test.js.snap
  src/components/Dashboard/Health/tests/__snapshots__/HealthItem.test.js.snap
  src/components/Dashboard/Inventory/InventoryItemStatus.js
  src/components/Dashboard/Inventory/tests/__snapshots__/InventoryItemStatus.test.js.snap
  src/components/Dashboard/Inventory/tests/__snapshots__/InventoryRow.test.js.snap
  src/components/Dashboard/tests/__snapshots__/Dashboard.api.test.js.snap
  src/components/StorageOverview/Alerts/tests/__snapshots__/Alerts.test.js.snap
  src/components/StorageOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/StorageOverview/DataResiliency/tests/__snapshots__/DataResiliency.test.js.snap
  src/components/StorageOverview/Details/Details.js
  src/components/StorageOverview/Details/tests/__snapshots__/Details.test.js.snap
  src/components/StorageOverview/Events/tests/__snapshots__/Events.test.js.snap
  src/components/StorageOverview/Inventory/tests/__snapshots__/Inventory.test.js.snap
  src/components/StorageOverview/OCSHealth/tests/__snapshots__/Health.test.js.snap
  src/components/StorageOverview/StorageOverview.js
  src/components/StorageOverview/TopConsumers/tests/__snapshots__/TopConsumers.test.js.snap
  src/components/StorageOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
Labels: size/XXL

#351 Use PF4 graphs
  package.json
  sass/components/Dashboard/capacity.scss
  sass/components/Dashboard/utilization.scss
  src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/Dashboard/Capacity/CapacityItem.js
  src/components/Dashboard/Capacity/tests/__snapshots__/CapacityItem.test.js.snap
  src/components/Dashboard/Utilization/UtilizationItem.js
  src/components/Dashboard/Utilization/tests/__snapshots__/UtilizationBody.test.js.snap
  src/components/Dashboard/Utilization/tests/__snapshots__/UtilizationItem.test.js.snap
  src/components/StorageOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/StorageOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
  yarn.lock
Labels: size/XXL

#364 Health Card Changes
  src/components/Dashboard/Health/HealthItem.js
  src/components/Dashboard/Health/tests/__snapshots__/HealthBody.test.js.snap
  src/components/Dashboard/Health/tests/__snapshots__/HealthItem.test.js.snap
  src/components/StorageOverview/OCSHealth/Health.js
  src/components/StorageOverview/OCSHealth/tests/__snapshots__/Health.test.js.snap
Labels: size/M

#365 Fix disk capacity prometheus metrics
  src/constants/storage.js
Labels: size/XS

#366 Update Cluster Overview Details prop format
  src/components/ClusterOverview/Details/Details.js
  src/components/ClusterOverview/Details/fixtures/Details.fixture.js
  src/selectors/prometheus/cluster.js
Labels: size/M

#332 Utilization: Disk IO RW chart
  src/components/ClusterOverview/Utilization/Utilization.js
  src/components/ClusterOverview/Utilization/fixtures/Utilization.fixture.js
  src/components/ClusterOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/Dashboard/Utilization/UtilizationItem.js
  src/constants/storage.js
Labels: size/L

#363 Enhance getHostStatus with additional resources
  src/components/BareMetalHosts/BaremetalHostStatus.js
  src/utils/status/host/hostStatus.js
Labels: size/M

#356 Add new host states
  src/components/BareMetalHosts/fixtures/BaremetalHostStatus.fixture.js
  src/components/BareMetalHosts/tests/BaremetalHostStatus.test.js
  src/components/BareMetalHosts/tests/__snapshots__/BaremetalHostStatus.test.js.snap
  src/utils/status/host/constants.js
Labels: size/L

#371 Add pf4 base css to cosmos
  sass/_dependencies.scss
Labels: size/XS

#367 Alignment and Color change
  sass/components/Dashboard/alert.scss
  sass/components/Dashboard/capacity.scss
  sass/components/Dashboard/health.scss
  sass/components/StorageOverview/data-resiliency.scss
  src/components/ClusterOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/Dashboard/Capacity/CapacityItem.js
  src/components/Dashboard/Capacity/tests/__snapshots__/CapacityItem.test.js.snap
  src/components/StorageOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
Labels: size/L

#360 fix(events): style updates
  sass/components/ClusterOverview/health.scss
  sass/components/Dashboard/consumers.scss
  sass/components/Dashboard/dashboard.scss
  sass/components/Dashboard/events.scss
  sass/components/Dashboard/utilization.scss
  src/components/ClusterOverview/Compliance/tests/__snapshots__/Compliance.test.js.snap
  src/components/ClusterOverview/Events/tests/__snapshots__/Events.test.js.snap
  src/components/ClusterOverview/Health/HealthBody.js
  src/components/ClusterOverview/Health/tests/__snapshots__/Health.test.js.snap
  src/components/ClusterOverview/Health/tests/__snapshots__/HealthBody.test.js.snap
  src/components/ClusterOverview/Inventory/tests/__snapshots__/Inventory.test.js.snap
  src/components/ClusterOverview/TopConsumers/tests/__snapshots__/TopConsumers.test.js.snap
  src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
  src/components/Dashboard/DashboardCard/DashboardCardTitleHelp.js
  src/components/Dashboard/DashboardCard/tests/__snapshots__/DashboardCardTitleHelp.test.js.snap
  src/components/Dashboard/tests/__snapshots__/Dashboard.api.test.js.snap
  src/components/StorageOverview/Events/tests/__snapshots__/Events.test.js.snap
  src/components/StorageOverview/Inventory/tests/__snapshots__/Inventory.test.js.snap
  src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
Labels: size/L

#376 Dashboards - Fix loading disks
  src/components/ClusterOverview/Inventory/Inventory.js
  src/components/Dashboard/Inventory/utils.js
  src/components/StorageOverview/Inventory/Inventory.js
  src/components/StorageOverview/Inventory/diskInventoryUtils.js
Labels: size/M

#372 Correct creation text for VM templates
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
Labels: size/XS

#374 Fix typo in Storage Performance card
  src/components/StorageOverview/Utilization/Utilization.js
  src/components/StorageOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
Labels: size/XS

#343 pod statuses: add the rest of kubernetes statuses
  src/utils/status/pod/constants.js
  src/utils/status/pod/fixtures/podStatus.fixture.js
  src/utils/status/pod/podStatus.js
  src/utils/status/vm/vmStatus.js
Labels: size/M

#378 Bump 0.1.29
  package.json
Labels: size/XS

#379 Update selector to get machine role
  src/components/BareMetalHosts/BaremetalHostRole.js
  src/components/BareMetalHosts/fixtures/BaremetalHostRole.fixture.js
  src/selectors/host/selectors.js
  src/selectors/machine/fixtures/selectors.fixture.js
  src/selectors/machine/index.js
  src/selectors/machine/selectors.js
  src/selectors/machine/tests/selectors.test.js
Labels: size/M

#362 Add subsystem health
  sass/components/ClusterOverview/compliance.scss
  sass/components/ClusterOverview/health.scss
  sass/components/Dashboard/health.scss
  src/components/ClusterOverview/ClusterOverview.js
  src/components/ClusterOverview/Compliance/Compliance.js
  src/components/ClusterOverview/Compliance/tests/__snapshots__/Compliance.test.js.snap
  src/components/ClusterOverview/Health/Health.js
  src/components/ClusterOverview/Health/HealthBody.js
  src/components/ClusterOverview/Health/fixtures/Health.fixture.js
  src/components/ClusterOverview/Health/tests/Health.test.js
  src/components/ClusterOverview/Health/tests/__snapshots__/Health.test.js.snap
  src/components/ClusterOverview/Health/tests/__snapshots__/HealthBody.test.js.snap
  src/components/ClusterOverview/fixtures/ClusterOverview.fixture.js
  src/components/Dashboard/DashboardCard/DashboardCardTitleSeeAll.js
  src/components/Dashboard/DashboardCard/fixtures/DashboardCardTitleSeeAll.fixture.js
  src/components/Dashboard/DashboardCard/index.js
  src/components/Dashboard/DashboardCard/tests/DashboardCardTitleSeeAll.test.js
  src/components/Dashboard/DashboardCard/tests/__snapshots__/DashboardCardTitleSeeAll.test.js.snap
  src/components/Dashboard/Health/HealthBody.js
  src/components/Dashboard/Health/HealthItem.js
  src/components/Dashboard/Health/strings.js
  src/components/Dashboard/Health/tests/__snapshots__/HealthBody.test.js.snap
  src/components/Dashboard/Health/tests/__snapshots__/HealthItem.test.js.snap
  src/components/Dashboard/Health/utils.js
  src/components/Dashboard/SubsystemHealth/SubsystemHealth.js
  src/components/Dashboard/SubsystemHealth/fixtures/SubsystemHealth.fixture.js
  src/components/Dashboard/SubsystemHealth/index.js
  src/components/Dashboard/SubsystemHealth/tests/SubsystemHealth.test.js
  src/components/Dashboard/SubsystemHealth/tests/__snapshots__/SubsystemHealth.test.js.snap
  src/components/StorageOverview/OCSHealth/Health.js
  src/components/StorageOverview/OCSHealth/strings.js
  src/components/StorageOverview/OCSHealth/tests/__snapshots__/Health.test.js.snap
Labels: size/XL

#381 Bump 0.1.30
  package.json
Labels: size/XS

#384 Add externally provisioned host status
  src/utils/status/host/constants.js
Labels: size/XS

#370 Render Add Host link as host status when in discovered state
  src/components/BareMetalHosts/BaremetalHostStatus.js
  src/components/BareMetalHosts/StatusComponents.js
  src/components/BareMetalHosts/fixtures/BaremetalHostStatus.fixture.js
  src/components/BareMetalHosts/fixtures/StatusComponents.fixture.js
  src/components/BareMetalHosts/tests/StatusComponents.test.js
  src/components/BareMetalHosts/tests/__snapshots__/BaremetalHostStatus.test.js.snap
  src/components/BareMetalHosts/tests/__snapshots__/StatusComponents.test.js.snap
Labels: size/M

#385 Fix parsing ocs health response
  src/components/ClusterOverview/Health/fixtures/Health.fixture.js
  src/components/Dashboard/Health/utils.js
Labels: size/S

#369 check if value is null for utilization graph
  src/components/Dashboard/Utilization/UtilizationItem.js
Labels: size/XS

#382 Remove Overview/HealthBody and use Dashboard/HealthBody in Compliace
  sass/components/ClusterOverview/compliance.scss
  sass/components/Dashboard/health.scss
  src/components/ClusterOverview/ClusterOverview.js
  src/components/ClusterOverview/Compliance/Compliance.js
  src/components/ClusterOverview/Compliance/tests/__snapshots__/Compliance.test.js.snap
  src/components/ClusterOverview/Health/Health.js
  src/components/ClusterOverview/Health/HealthBody.js
  src/components/ClusterOverview/Health/fixtures/HealthBody.fixture.js
  src/components/ClusterOverview/index.js
  src/components/Dashboard/DashboardCard/fixtures/DashboardCardTitleSeeAll.fixture.js
  src/components/Dashboard/Health/HealthItem.js
Labels: size/L

#387 Introduce hardware host selectors
  src/selectors/host/selectors.js
Labels: size/XS

#389 Hotfix missing components/ClusterOverview/compliance
  sass/_components.scss
Labels: size/XS

#394 Changed openshift name to CamelCase
  src/components/ClusterOverview/Details/Details.js
  src/components/ClusterOverview/Details/tests/__snapshots__/Details.test.js.snap
  src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
Labels: size/XS

#395 Fixed css issue with top projects card
  src/components/StorageOverview/TopConsumers/TopConsumers.js
Labels: size/XS

#397 bug fix: progress bar showing resiliency percentage above 100%
  src/components/StorageOverview/DataResiliency/DataResiliency.js
Labels: size/XS

#398 Remove whitespace from kubevirt.ui/firstBoot annotation
  src/constants/index.js
Labels: size/XS

#393 fix card heights
  sass/components/ClusterOverview/health.scss
  sass/components/Dashboard/events.scss
Labels: size/S

#399 Bump 0.1.33
  package.json
Labels: size/XS

#400 remove superflous scss import
  sass/_components.scss
Labels: size/XS

#401 Fixed the x-axis sequence issue for top projects card
  src/components/StorageOverview/TopConsumers/TopConsumers.js
  src/selectors/prometheus/storage.js
Labels: size/S

#403 Fixed the x-axis sequence issue for top projects card
  src/components/StorageOverview/TopConsumers/TopConsumers.js
  src/selectors/prometheus/storage.js
Labels: size/S

#405 Change to y axis of Top Projects card
  src/components/StorageOverview/TopConsumers/TopConsumers.js
Labels: size/XS

#396 Drop VM detail edit values on cancel
  src/components/Details/VmDetails/VmDetails.js
Labels: size/S

#408 Show description of alert if available
  src/components/Dashboard/Alert/AlertItem.js
  src/selectors/prometheus/alerts.js
Labels: size/XS

#383 details/charts
  sass/components/ClusterOverview/health.scss
  sass/components/Dashboard/capacity.scss
  sass/components/Dashboard/detail.scss
  sass/components/Dashboard/events.scss
  sass/components/StorageOverview/data-resiliency.scss
  src/components/ClusterOverview/Details/tests/__snapshots__/Details.test.js.snap
  src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
  src/components/Dashboard/Details/DetailsBody.js
  src/components/Dashboard/Details/tests/__snapshots__/DetailsBody.test.js.snap
  src/components/StorageOverview/Capacity/Capacity.js
  src/components/StorageOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/StorageOverview/Details/tests/__snapshots__/Details.test.js.snap
  src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
Labels: size/M

#409 css updates for details/charts (#383)
  sass/components/ClusterOverview/health.scss
  sass/components/Dashboard/capacity.scss
  sass/components/Dashboard/detail.scss
  sass/components/Dashboard/events.scss
  sass/components/StorageOverview/data-resiliency.scss
  src/components/ClusterOverview/Details/tests/__snapshots__/Details.test.js.snap
  src/components/ClusterOverview/tests/__snapshots__/ClusterOverview.test.js.snap
  src/components/Dashboard/Details/DetailsBody.js
  src/components/Dashboard/Details/tests/__snapshots__/DetailsBody.test.js.snap
  src/components/StorageOverview/Capacity/Capacity.js
  src/components/StorageOverview/Capacity/tests/__snapshots__/Capacity.test.js.snap
  src/components/StorageOverview/Details/tests/__snapshots__/Details.test.js.snap
  src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
Labels: size/M

#410 Show description of alert if available
  src/components/Dashboard/Alert/AlertItem.js
  src/selectors/prometheus/alerts.js
Labels: size/XS

#404 Add selectors for node maintenance
  src/components/BareMetalHosts/index.js
  src/selectors/node/combined.js
  src/selectors/node/index.js
Labels: size/S

#411 plotted y values for performance card graphs
  src/components/Dashboard/Utilization/UtilizationItem.js
  src/components/StorageOverview/Utilization/Utilization.js
  src/components/StorageOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
Labels: size/XL

#412 Plotted y values for performance card graphs
  src/components/Dashboard/Utilization/UtilizationItem.js
  src/components/StorageOverview/Utilization/Utilization.js
  src/components/StorageOverview/Utilization/tests/__snapshots__/Utilization.test.js.snap
  src/components/StorageOverview/tests/__snapshots__/StorageOverview.test.js.snap
Labels: size/XL

#413 Fix dashboard health typo - degrated/degraded
  src/components/ClusterOverview/Health/Health.js
  src/components/ClusterOverview/Health/tests/__snapshots__/Health.test.js.snap
Labels: size/XS

#414 Fix dashboard health typo - degrated/degraded
  src/components/ClusterOverview/Health/Health.js
  src/components/ClusterOverview/Health/tests/__snapshots__/Health.test.js.snap
Labels: size/XS

#415 Bump 0.1.33-1
  package.json
Labels: size/XS

#406 v2v: fix connecting to new instance & enhance
  src/components/Wizard/CreateVmWizard/providers/VCenterInstances.js
  src/components/Wizard/CreateVmWizard/providers/VCenterVms.js
  src/config/index.js
  src/k8s/objects/v2v/vmware/conversionPod.js
  src/k8s/objects/v2v/vmware/vmWareDeployment.js
Labels: size/S

#407 enhance k8s methods
  sass/components/Wizard/create-vm-wizard.scss
  src/components/VmConsoles/tests/__snapshots__/DesktopViewerSelector.test.js.snap
  src/components/Wizard/CreateVmWizard/CreateVmWizard.js
  src/components/Wizard/CreateVmWizard/ResultTabRow.js
  src/components/Wizard/CreateVmWizard/fixtures/ResultTabRow.fixture.js
  src/components/Wizard/CreateVmWizard/strings.js
  src/components/Wizard/CreateVmWizard/tests/__snapshots__/ResultTabRow.test.js.snap
  src/k8s/request.js
  src/k8s/requests/v2v/importVmware.js
  src/k8s/selectors.js
  src/k8s/tests/request.test.js
  src/k8s/util/enhancedK8sMethods.js
  src/k8s/util/errors.js
  src/k8s/util/index.js
  src/k8s/util/tests/enhancedK8sMethods.test.js
  src/k8s/util/utils.js
  src/tests/mocks/vm/vm.mock.js
  src/utils/utils.js
Labels: size/XXL

#418 revert yarn.lock
  yarn.lock
Labels: size/S

#416 Add status component
  sass/_components.scss
  sass/components/HostStatus/host-status.scss
  sass/components/Status/status.scss
  sass/components/VmStatus/vm-status.scss
  src/components/BareMetalHosts/StatusComponents.js
  src/components/BareMetalHosts/tests/__snapshots__/StatusComponents.test.js.snap
  src/components/Details/VmDetails/tests/__snapshots__/VmDetails.test.js.snap
  src/components/NodeStatus/NodeStatus.js
  src/components/NodeStatus/fixtures/NodeStatus.fixture.js
  src/components/NodeStatus/index.js
  src/components/NodeStatus/tests/NodeStatus.test.js
  src/components/NodeStatus/tests/__snapshots__/NodeStatus.test.js.snap
  src/components/Status/Status.js
  src/components/Status/fixtures/Status.fixture.js
  src/components/Status/index.js
  src/components/Status/tests/Status.test.js
  src/components/Status/tests/__snapshots__/Status.test.js.snap
  src/components/VmStatus/VmStatus.js
  src/components/VmStatus/tests/__snapshots__/VmStatus.test.js.snap
  src/index.js
  src/models/index.js
  src/selectors/common.js
  src/selectors/node/combined.js
  src/utils/status/node/constants.js
  src/utils/status/node/nodeStatus.js
Labels: size/XL

#421 v2v: Compose image name dynamically
  src/config/index.js
  src/k8s/objects/v2v/vmware/conversionPod.js
  src/k8s/objects/v2v/vmware/vmWareDeployment.js
  src/k8s/requests/v2v/startV2VvmwareController.js
Labels: size/S

#422 v2v: Compose image name dynamically
  src/config/index.js
  src/k8s/objects/v2v/vmware/conversionPod.js
  src/k8s/objects/v2v/vmware/vmWareDeployment.js
  src/k8s/requests/v2v/startV2VvmwareController.js
Labels: size/S
